Borneo Exotics,BE-3001,alata, , ,
Borneo Exotics,BE-3002,albomarginata, , ,
Borneo Exotics,BE-3003,albomarginata, , ,
Borneo Exotics,BE-3004,albomarginata , , ,
Borneo Exotics,BE-3005,albomarginata , , ,
Borneo Exotics,BE-3360,albomarginata , , ,
Borneo Exotics,BE-3576,albomarginata , , ,
Borneo Exotics,BE-3006,ampullaria, , ,
Borneo Exotics,BE-3007,ampullaria, , ,
Borneo Exotics,BE-3009,ampullaria, , ,
Borneo Exotics,BE-3011,ampullaria, , ,
Borneo Exotics,BE-3012,ampullaria, , ,
Borneo Exotics,BE-3013,ampullaria, , ,
Borneo Exotics,BE-3014,ampullaria, , ,
Borneo Exotics,BE-3015,ampullaria, , ,
Borneo Exotics,BE-3016,ampullaria, , ,
Borneo Exotics,BE-3282,ampullaria, , ,
Borneo Exotics,BE-3283,ampullaria, , ,
Borneo Exotics,BE-3285,ampullaria, , ,
Borneo Exotics,BE-3286,ampullaria, , ,
Borneo Exotics,BE-3287,ampullaria, , ,
Borneo Exotics,BE-3288,ampullaria, , ,
Borneo Exotics,BE-3304,ampullaria, , ,
Borneo Exotics,BE-3390,ampullaria, , ,
Borneo Exotics,BE-3450,ampullaria, , ,
Borneo Exotics,BE-3494,ampullaria, , ,
Borneo Exotics,BE-3659,ampullaria, , ,
Borneo Exotics,BE-3681,ampullaria, , ,
Borneo Exotics,BE-3018,anamensis , , ,
Borneo Exotics,BE-3021,argentii, , ,
Borneo Exotics,BE-3023,aristolochioides , , ,
Borneo Exotics,BE-4544,aristolochioides , , ,
Borneo Exotics,BE-4547,aristolochioides , , ,
Borneo Exotics,BE-3026,bellii , , ,
Borneo Exotics,BE-3029,bicalcarata, , ,
Borneo Exotics,BE-3031,bicalcarata, , ,
Borneo Exotics,BE-3335,bicalcarata, , ,
Borneo Exotics,BE-3336,bicalcarata, , ,
Borneo Exotics,BE-3356,bicalcarata, , ,
Borneo Exotics,BE-3682,bicalcarata, , ,
Borneo Exotics,BE-3036,bongso , , ,
Borneo Exotics,BE-3039,boschiana, , ,
Borneo Exotics,BE-3040,boschiana, , ,
Borneo Exotics,BE-3448,boschiana, , ,
Borneo Exotics,BE-3643,boschiana, , ,
Borneo Exotics,BE-3041,burbidgeae , , ,
Borneo Exotics,BE-3042,burbidgeae , , ,
Borneo Exotics,BE-3848,burbidgeae , , ,
Borneo Exotics,BE-3873,burbidgeae , , ,
Borneo Exotics,BE-3044,campanulata, , ,
Borneo Exotics,BE-3046,copelandii , , ,
Borneo Exotics,BE-3047,copelandii , , ,
Borneo Exotics,BE-3242,copelandii , , ,
Borneo Exotics,BE-3243,copelandii , , ,
Borneo Exotics,BE-3050,danseri, , ,
Borneo Exotics,BE-3051,densiflora , , ,
Borneo Exotics,BE-3052,densiflora , , ,
Borneo Exotics,BE-3837,densiflora , , ,
Borneo Exotics,BE-3055,diatas , , ,
Borneo Exotics,BE-3056,diatas , , ,
Borneo Exotics,BE-3861,diatas , , ,
Borneo Exotics,BE-3057,distillatoria, , ,
Borneo Exotics,BE-3061,distillatoria, , ,
Borneo Exotics,BE-3064,ephippiata , , ,
Borneo Exotics,BE-3065,eustachya, , ,
Borneo Exotics,BE-3067,maxima , , ,
Borneo Exotics,BE-3110,maxima , , ,
Borneo Exotics,BE-3112,maxima , , ,
Borneo Exotics,BE-3303,maxima , , ,
Borneo Exotics,BE-3311,maxima , , ,
Borneo Exotics,BE-3319,maxima , , ,
Borneo Exotics,BE-3433,maxima , , ,
Borneo Exotics,BE-3496,maxima , , ,
Borneo Exotics,BE-3735,maxima , , ,
Borneo Exotics,BE-3786,maxima , , ,
Borneo Exotics,BE-3907,maxima , , ,
Borneo Exotics,BE-4081,maxima , , ,
Borneo Exotics,BE-3068,fusca, , ,
Borneo Exotics,BE-3069,fusca, , ,
Borneo Exotics,BE-3070,fusca, , ,
Borneo Exotics,BE-3465,fusca, , ,
Borneo Exotics,BE-3074,gracilis , , ,
Borneo Exotics,BE-4060,gracilis , , ,
Borneo Exotics,BE-4611,gracilis , , ,
Borneo Exotics,BE-3077,gymnamphora, , ,
Borneo Exotics,BE-3078,gymnamphora, , ,
Borneo Exotics,BE-3236,gymnamphora, , ,
Borneo Exotics,BE-3241,gymnamphora, , ,
Borneo Exotics,BE-3908,gymnamphora, , ,
Borneo Exotics,BE-4059,gymnamphora, , ,
Borneo Exotics,BE-3082,hamata , , ,
Borneo Exotics,BE-3280,hamata , , ,
Borneo Exotics,BE-3380,hamata , , ,
Borneo Exotics,BE-3382,hamata , , ,
Borneo Exotics,BE-3495,hamata , , ,
Borneo Exotics,BE-3715,hamata , , ,
Borneo Exotics,BE-3975,hamata , , ,
Borneo Exotics,BE-4015,hamata , , ,
Borneo Exotics,BE-4044,hamata , , ,
Borneo Exotics,BE-3083,hirsuta, , ,
Borneo Exotics,BE-3084,inermis, , ,
Borneo Exotics,BE-3085,inermis, , ,
Borneo Exotics,BE-3089,insignis , , ,
Borneo Exotics,BE-3090,izumiae, , ,
Borneo Exotics,BE-3925,izumiae, , ,
Borneo Exotics,BE-3092,jacquelineae , , ,
Borneo Exotics,BE-3096,jacquelineae , , ,
Borneo Exotics,BE-3874,jacquelineae , , ,
Borneo Exotics,BE-3098,khasiana , , ,
Borneo Exotics,BE-3099,lamii, , ,
Borneo Exotics,BE-3100,lowii, , ,
Borneo Exotics,BE-3103,macfarlanei, , ,
Borneo Exotics,BE-3106,macrophylla, , ,
Borneo Exotics,BE-3107,macrovulgaris, , ,
Borneo Exotics,BE-3109,madagascariensis , , ,
Borneo Exotics,BE-3247,madagascariensis , , ,
Borneo Exotics,BE-3117,merrilliana, , ,
Borneo Exotics,BE-3337,merrilliana, , ,
Borneo Exotics,BE-3493,merrilliana, , ,
Borneo Exotics,BE-3727,merrilliana, , ,
Borneo Exotics,BE-3121,mikei, , ,
Borneo Exotics,BE-3506,mikei, , ,
Borneo Exotics,BE-3122,mindanaoensis, , ,
Borneo Exotics,BE-3123,mira , , ,
Borneo Exotics,BE-3362,mira , , ,
Borneo Exotics,BE-3979,mira , , ,
Borneo Exotics,BE-3135,petiolata, , ,
Borneo Exotics,BE-3913,petiolata, , ,
Borneo Exotics,BE-3136,philippinensis , , ,
Borneo Exotics,BE-3141,rafflesiana, , ,
Borneo Exotics,BE-3144,rafflesiana, , ,
Borneo Exotics,BE-3146,rafflesiana, , ,
Borneo Exotics,BE-3147,rafflesiana, , ,
Borneo Exotics,BE-3148,rafflesiana, , ,
Borneo Exotics,BE-3351,rafflesiana, , ,
Borneo Exotics,BE-3352,rafflesiana, , ,
Borneo Exotics,BE-3353,rafflesiana, , ,
Borneo Exotics,BE-3402,rafflesiana, , ,
Borneo Exotics,BE-3451,rafflesiana, , ,
Borneo Exotics,BE-3475,rafflesiana, , ,
Borneo Exotics,BE-3722,rafflesiana, , ,
Borneo Exotics,BE-4519,rafflesiana, , ,
Borneo Exotics,BE-4571,rafflesiana, , ,
Borneo Exotics,BE-3151,neoguineensis, , ,
Borneo Exotics,BE-3393,neoguineensis, , ,
Borneo Exotics,BE-4539,neoguineensis, , ,
Borneo Exotics,BE-3152,rajah, , ,
Borneo Exotics,BE-3155,ramispina, , ,
Borneo Exotics,BE-3929,ramispina, , ,
Borneo Exotics,BE-3159,reinwardtiana, , ,
Borneo Exotics,BE-3671,reinwardtiana, , ,
Borneo Exotics,BE-3162,sanguinea, , ,
Borneo Exotics,BE-3312,sanguinea, , ,
Borneo Exotics,BE-4066,sanguinea, , ,
Borneo Exotics,BE-3164,sibuyanensis , , ,
Borneo Exotics,BE-3972,sibuyanensis , , ,
Borneo Exotics,BE-4029,sibuyanensis , , ,
Borneo Exotics,BE-3169,singalana, , ,
Borneo Exotics,BE-3170,singalana, , ,
Borneo Exotics,BE-3248,singalana, , ,
Borneo Exotics,BE-3761,singalana, , ,
Borneo Exotics,BE-3171,smilesii , , ,
Borneo Exotics,BE-3313,smilesii , , ,
Borneo Exotics,BE-3316,smilesii , , ,
Borneo Exotics,BE-3358,smilesii , , ,
Borneo Exotics,BE-3172,sp. #1 , , ,
Borneo Exotics,BE-3173,sp. #2 , , ,
Borneo Exotics,BE-3174,spathulata , , ,
Borneo Exotics,BE-3175,spathulata , , ,
Borneo Exotics,BE-3176,spectabilis, , ,
Borneo Exotics,BE-3177,spectabilis, , ,
Borneo Exotics,BE-3178,spectabilis, , ,
Borneo Exotics,BE-3179,spectabilis, , ,
Borneo Exotics,BE-3321,spectabilis, , ,
Borneo Exotics,BE-3322,spectabilis, , ,
Borneo Exotics,BE-3768,spectabilis, , ,
Borneo Exotics,BE-3186,sumatrana, , ,
Borneo Exotics,BE-4540,sumatrana, , ,
Borneo Exotics,BE-3187,talangensis, , ,
Borneo Exotics,BE-3835,talangensis, , ,
Borneo Exotics,BE-4075,talangensis, , ,
Borneo Exotics,BE-3191,tentaculata, , ,
Borneo Exotics,BE-3192,tentaculata, , ,
Borneo Exotics,BE-3193,tentaculata, , ,
Borneo Exotics,BE-3194,tentaculata, , ,
Borneo Exotics,BE-3870,tentaculata, , ,
Borneo Exotics,BE-3196,tobaica, , ,
Borneo Exotics,BE-3198,tobaica, , ,
Borneo Exotics,BE-3259,tobaica, , ,
Borneo Exotics,BE-3260,tobaica, , ,
Borneo Exotics,BE-3261,tobaica, , ,
Borneo Exotics,BE-3264,tobaica, , ,
Borneo Exotics,BE-4089,tobaica, , ,
Borneo Exotics,BE-3200,tomoriana, , ,
Borneo Exotics,BE-3338,tomoriana, , ,
Borneo Exotics,BE-3342,tomoriana, , ,
Borneo Exotics,BE-3343,tomoriana, , ,
Borneo Exotics,BE-3344,tomoriana, , ,
Borneo Exotics,BE-3202,truncata , , ,
Borneo Exotics,BE-3203,truncata , , ,
Borneo Exotics,BE-3204,truncata , , ,
Borneo Exotics,BE-4001,truncata , , ,
Borneo Exotics,BE-3205,veitchii , , ,
Borneo Exotics,BE-3207,veitchii , , ,
Borneo Exotics,BE-3482,veitchii , , ,
Borneo Exotics,BE-3646,veitchii , , ,
Borneo Exotics,BE-3734,veitchii , , ,
Borneo Exotics,BE-4021,veitchii , , ,
Borneo Exotics,BE-4033,veitchii , , ,
Borneo Exotics,BE-4068,veitchii , , ,
Borneo Exotics,BE-4087,veitchii , , ,
Borneo Exotics,BE-4093,veitchii , , ,
Borneo Exotics,BE-4094,veitchii , , ,
Borneo Exotics,BE-4095,veitchii , , ,
Borneo Exotics,BE-4096,veitchii , , ,
Borneo Exotics,BE-4097,veitchii , , ,
Borneo Exotics,BE-3215,ventricosa , , ,
Borneo Exotics,BE-3217,ventricosa , , ,
Borneo Exotics,BE-3278,ventricosa , , ,
Borneo Exotics,BE-3645,ventricosa , , ,
Borneo Exotics,BE-3771,ventricosa , , ,
Borneo Exotics,BE-3772,ventricosa , , ,
Borneo Exotics,BE-3224,vieillardii, , ,
Borneo Exotics,BE-4599,vieillardii, , ,
Borneo Exotics,BE-3225,villosa, , ,
Borneo Exotics,BE-3254,burkei , , ,
Borneo Exotics,BE-4512,burkei , , ,
Borneo Exotics,BE-4527,burkei , , ,
Borneo Exotics,BE-3256,vogelii, , ,
Borneo Exotics,BE-3257,glabrata , , ,
Borneo Exotics,BE-4592,glabrata , , ,
Borneo Exotics,BE-3266,platychila , , ,
Borneo Exotics,BE-3503,platychila , , ,
Borneo Exotics,BE-4065,platychila , , ,
Borneo Exotics,BE-3276,jamban , , ,
Borneo Exotics,BE-3875,jamban , , ,
Borneo Exotics,BE-3277,lingulata, , ,
Borneo Exotics,BE-3463,lingulata, , ,
Borneo Exotics,BE-3299,alba , , ,
Borneo Exotics,BE-3307,robcantleyi, , ,
Borneo Exotics,BE-3517,robcantleyi, , ,
Borneo Exotics,BE-3308,mollis , , ,
Borneo Exotics,BE-3340,treubiana, , ,
Borneo Exotics,BE-3341,treubiana, , ,
Borneo Exotics,BE-3346,thai , , ,
Borneo Exotics,BE-3364,thai , , ,
Borneo Exotics,BE-3347,kerrii , , ,
Borneo Exotics,BE-3350,adnata , , ,
Borneo Exotics,BE-3357,northiana, , ,
Borneo Exotics,BE-3363,mirabilis var. echinostoma, , ,
Borneo Exotics,BE-3372,mirabilis var. echinostoma, , ,
Borneo Exotics,BE-3370,rowanae , , ,
Borneo Exotics,BE-3392,kongkandana , , ,
Borneo Exotics,BE-3394,mirabilis var. globosa, , ,
Borneo Exotics,BE-3852,mirabilis var. globosa, , ,
Borneo Exotics,BE-3928,mirabilis var. globosa, , ,
Borneo Exotics,BE-3397,chang , , ,
Borneo Exotics,BE-3403,mirabilis , , ,
Borneo Exotics,BE-3439,attenboroughii, , ,
Borneo Exotics,BE-3693,attenboroughii, , ,
Borneo Exotics,BE-3452,klossii , , ,
Borneo Exotics,BE-3502,klossii , , ,
Borneo Exotics,BE-4014,klossii , , ,
Borneo Exotics,BE-3572,dubia , , ,
Borneo Exotics,BE-3651,palawanensis, , ,
Borneo Exotics,BE-4013,palawanensis, , ,
Borneo Exotics,BE-3652,flava , , ,
Borneo Exotics,BE-3673,chaniana, , ,
Borneo Exotics,BE-3691,glandulifera, , ,
Borneo Exotics,BE-3766,glandulifera, , ,
Borneo Exotics,BE-3879,glandulifera, , ,
Borneo Exotics,BE-3704,longifolia, , ,
Borneo Exotics,BE-3736,eymae , , ,
Borneo Exotics,BE-3770,aenigma , , ,
Borneo Exotics,BE-3839,pervillei , , ,
Borneo Exotics,BE-3856,bokorensis, , ,
Borneo Exotics,BE-3857,bokorensis, , ,
Borneo Exotics,BE-3858,bokorensis, , ,
Borneo Exotics,BE-4518,bokorensis, , ,
Borneo Exotics,BE-3905,stenophylla , , ,
Borneo Exotics,BE-3919,ovata , , ,
Borneo Exotics,BE-4084,ovata , , ,
Borneo Exotics,BE-3921,mollis, , ,
Borneo Exotics,BE-3956,ceciliae, , ,
Borneo Exotics,BE-4600,ceciliae, , ,
Borneo Exotics,BE-4025,peltata , , ,
Borneo Exotics,BE-4613,peltata , , ,
Borneo Exotics,BE-4049,tenuis, , ,
Borneo Exotics,BE-4058,clipeata, , ,
Borneo Exotics,BE-4607,nigra , , ,
Andreas Wistuba,AW-N_gma.01,alba , , ,
Andreas Wistuba,AW-N_amp_Sdw.RSC,ampullaria, , ,
Andreas Wistuba,AW-N_amp_Sdw.Langtrieb,ampullaria, , ,
Andreas Wistuba,AW-N_arg.07,argentii , , ,
Andreas Wistuba,AW-N_arg.08,argentii , , ,
Andreas Wistuba,AW-N_arg.09,argentii , , ,
Andreas Wistuba,AW-N_arg.11,argentii , , ,
Andreas Wistuba,AW-N_arg.13,argentii , , ,
Andreas Wistuba,AW-N_att.513,attenboroughii, , ,
Andreas Wistuba,AW-N_att.515,attenboroughii, , ,
Andreas Wistuba,AW-N_bic.02F,bicalcarata , , ,
Andreas Wistuba,AW-N_bong_JN.01,bongso , , ,
Andreas Wistuba,AW-N_bosch.ISC,boschiana , , ,
Andreas Wistuba,AW-N_carunc_Sag.01,carunculata , , ,
Andreas Wistuba,AW-N_carunc_Sag.RC,carunculata , , ,
Andreas Wistuba,AW-N_carunc_r.01,carunculata , , ,
Andreas Wistuba,AW-N_chan.01,chaniana, , ,
Andreas Wistuba,AW-N_chan.02,chaniana, , ,
Andreas Wistuba,AW-N_chan.04,chaniana, , ,
Andreas Wistuba,AW-N_chan.05,chaniana, , ,
Andreas Wistuba,AW-N_chan.MT01,chaniana, , ,
Andreas Wistuba,AW-N_chan.RSC,chaniana , , ,
Andreas Wistuba,AW-N_chan.RC,chaniana, , ,
Andreas Wistuba,AW-N_corn.01,cornuta , , ,
Andreas Wistuba,AW-N_corn.RC,cornuta , , ,
Andreas Wistuba,AW-N_dact_faiz.01,dactylifera, , ,
Andreas Wistuba,AW-N_RHH.01,diabolica, , ,
Andreas Wistuba,AW-N_RHH.02,diabolica, , ,
Andreas Wistuba,AW-N_RHH.03,diabolica, , ,
Andreas Wistuba,AW-N_RHH.04,diabolica, , ,
Andreas Wistuba,AW-N_RHH.05,diabolica, , ,
Andreas Wistuba,AW-N_RHH.07,diabolica, , ,
Andreas Wistuba,AW-N_RHH.09,diabolica, , ,
Andreas Wistuba,AW-N_RHH.13,diabolica, , ,
Andreas Wistuba,AW-N_RHH.14,diabolica, , ,
Andreas Wistuba,AW-N_RHH.ISC,diabolica , , ,
Andreas Wistuba,AW-N_dub_T.02,dubia, , ,
Andreas Wistuba,AW-N_dub_T.03,dubia, , ,
Andreas Wistuba,AW-N_dub_T.14,dubia, , ,
Andreas Wistuba,AW-N_dub_T.Langtrieb,dubia , , ,
Andreas Wistuba,AW-N_dub_M.01,dubia, , ,
Andreas Wistuba,AW-N_dub_M.03,dubia, , ,
Andreas Wistuba,AW-N_dub_M.04,dubia, , ,
Andreas Wistuba,AW-N_dub_M.06,dubia, , ,
Andreas Wistuba,AW-N_dub_M.09,dubia, , ,
Andreas Wistuba,AW-N_dub_M.RSC,dubia , , ,
Andreas Wistuba,AW-N_dub_M.Langtrieb,dubia , , ,
Andreas Wistuba,AW-N_ephi_R.01,ephippiata, , ,
Andreas Wistuba,AW-N_ephi_R.02,ephippiata, , ,
Andreas Wistuba,AW-N_ephi_R.04,ephippiata, , ,
Andreas Wistuba,AW-N_ephi_R.05,ephippiata, , ,
Andreas Wistuba,AW-N_ephi_HM.RSC,ephippiata, , ,
Andreas Wistuba,AW-N_epiphy.01,epiphytica, , ,
Andreas Wistuba,AW-N_epiphy.ISC,epiphytica , , ,
Andreas Wistuba,AW-N_epiphy.RC,epiphytica, , ,
Andreas Wistuba,AW-N_ey.01,eymae , , ,
Andreas Wistuba,AW-N_ey.02,eymae , , ,
Andreas Wistuba,AW-N_ey.03,eymae , , ,
Andreas Wistuba,AW-N_ey.04,eymae , , ,
Andreas Wistuba,AW-N_ey.05,eymae , , ,
Andreas Wistuba,AW-N_ey.06,eymae , , ,
Andreas Wistuba,AW-N_ey.07,eymae , , ,
Andreas Wistuba,AW-N_ey.08,eymae , , ,
Andreas Wistuba,AW-N_ey.Lumut_Hort_01,eymae, , ,
Andreas Wistuba,AW-N_ey.RC,eymae , , ,
Andreas Wistuba,AW-N_fal.01,fallax , , ,
Andreas Wistuba,AW-N_flav.02A,flava, , ,
Andreas Wistuba,AW-N_flav.RSC,flava, , ,
Andreas Wistuba,AW-N_flav.RC,flava , , ,
Andreas Wistuba,AW-N_fusc_Kem.02,fusca , , ,
Andreas Wistuba,AW-N_fusc_Kem.04,fusca , , ,
Andreas Wistuba,AW-N_fusc_Kem.05,fusca , , ,
Andreas Wistuba,AW-N_fusc_Kem.08,fusca , , ,
Andreas Wistuba,AW-N_glab_KatG.01,glabrata , , ,
Andreas Wistuba,AW-N_glandu_MT.01,glandulifera , , ,
Andreas Wistuba,AW-N_glandu_MT.ISC,glandulifera, , ,
Andreas Wistuba,AW-N_glandu_MT.RC,glandulifera , , ,
Andreas Wistuba,AW-N_glob.03,globosa , , ,
Andreas Wistuba,AW-N_glob.04,globosa , , ,
Andreas Wistuba,AW-N_glob.05,globosa , , ,
Andreas Wistuba,AW-N_glob.07,globosa , , ,
Andreas Wistuba,AW-N_grac_Beau.ISC,gracilis, , ,
Andreas Wistuba,AW-N_gym_T.01,gymnamphora, , ,
Andreas Wistuba,AW-N_gym_T.RC,gymnamphora, , ,
Andreas Wistuba,AW-N_ham.01,hamata , , ,
Andreas Wistuba,AW-N_ham.02,hamata , , ,
Andreas Wistuba,AW-N_ham.03,hamata , , ,
Andreas Wistuba,AW-N_ham.ISC,hamata, , ,
Andreas Wistuba,AW-N_inerm.09,inermis, , ,
Andreas Wistuba,AW-N_inerm.10,inermis, , ,
Andreas Wistuba,AW-N_inerm.11,inermis, , ,
Andreas Wistuba,AW-N_inerm.Langtrieb,inermis , , ,
Andreas Wistuba,AW-N_inerm.RC,inermis, , ,
Andreas Wistuba,AW-N_iz.01,izumiae , , ,
Andreas Wistuba,AW-N_iz.04,izumiae , , ,
Andreas Wistuba,AW-N_iz.06,izumiae , , ,
Andreas Wistuba,AW-N_iz.07,izumiae , , ,
Andreas Wistuba,AW-N_iz.09,izumiae , , ,
Andreas Wistuba,AW-N_jaq_1-04.04,jacquelineae, , ,
Andreas Wistuba,AW-N_jaq_1-04.05,jacquelineae, , ,
Andreas Wistuba,AW-N_jaq_1-04.07,jacquelineae, , ,
Andreas Wistuba,AW-N_jaq_1-04.10,jacquelineae, , ,
Andreas Wistuba,AW-N_jamb_TG.RSC,jamban, , ,
Andreas Wistuba,AW-N_khas.01,khasiana, , ,
Andreas Wistuba,AW-N_lam_Dor.02,lamii, , ,
Andreas Wistuba,AW-N_lam_Dor.Y,lamii , , ,
Andreas Wistuba,AW-N_lam_Dor.E,lamii , , ,
Andreas Wistuba,AW-N_lam_Dor.W,lamii , , ,
Andreas Wistuba,AW-N_lam_Dor.T,lamii , , ,
Andreas Wistuba,AW-N_lam_Dor.Z,lamii , , ,
Andreas Wistuba,AW-N_lam_Dor.U,lamii , , ,
Andreas Wistuba,AW-N_lav.02,lavicola , , ,
Andreas Wistuba,AW-N_lav.03,lavicola , , ,
Andreas Wistuba,AW-N_lav.ISC,lavicola, , ,
Andreas Wistuba,AW-N_leo.01,leonardoi, , ,
Andreas Wistuba,AW-N_leo.02,leonardoi, , ,
Andreas Wistuba,AW-N_leo.03,leonardoi, , ,
Andreas Wistuba,AW-N_leo.04,leonardoi, , ,
Andreas Wistuba,AW-N_leo.05,leonardoi, , ,
Andreas Wistuba,AW-N_low_BL.RSC,lowii, , ,
Andreas Wistuba,AW-N_low_Ment.01,lowii , , ,
Andreas Wistuba,AW-N_low_Ment.02,lowii , , ,
Andreas Wistuba,AW-N_low_Ment.03,lowii , , ,
Andreas Wistuba,AW-N_low_Ment.04,lowii , , ,
Andreas Wistuba,AW-N_low_Ment.05,lowii , , ,
Andreas Wistuba,AW-N_low_Ment.06,lowii , , ,
Andreas Wistuba,AW-N_low_Ment.07,lowii , , ,
Andreas Wistuba,AW-N_low_Ment.08,lowii , , ,
Andreas Wistuba,AW-N_low_Ment.09,lowii , , ,
Andreas Wistuba,AW-N_low_Ment.10,lowii , , ,
Andreas Wistuba,AW-N_low_mul.07,lowii, , ,
Andreas Wistuba,AW-N_low_mul.ISC,lowii , , ,
Andreas Wistuba,AW-N_low_trus.01,lowii , , ,
Andreas Wistuba,AW-N_low_trus.03,lowii , , ,
Andreas Wistuba,AW-N_low_trus.04,lowii , , ,
Andreas Wistuba,AW-N_low_trus.05,lowii , , ,
Andreas Wistuba,AW-N_low_trus.06,lowii , , ,
Andreas Wistuba,AW-N_low_trus.ISC,lowii, , ,
Andreas Wistuba,AW-N_macro.WT_01,macrophylla , , ,
Andreas Wistuba,AW-N_macro.WT_02,macrophylla , , ,
Andreas Wistuba,AW-N_macro.WT_03,macrophylla , , ,
Andreas Wistuba,AW-N_macro.WT_04,macrophylla , , ,
Andreas Wistuba,AW-N_macro.WT_05,macrophylla , , ,
Andreas Wistuba,AW-N_macro.05,macrophylla, , ,
Andreas Wistuba,AW-N_macro.WT_06,macrophylla , , ,
Andreas Wistuba,AW-N_macro.WT_07,macrophylla , , ,
Andreas Wistuba,AW-N_macro.WT_08,macrophylla , , ,
Andreas Wistuba,AW-N_macro.WT_09,macrophylla , , ,
Andreas Wistuba,AW-N_macro.WT_10,macrophylla , , ,
Andreas Wistuba,AW-N_macro.T,macrophylla , , ,
Andreas Wistuba,AW-N_macro.ed1,macrophylla , , ,
Andreas Wistuba,AW-N_mant.01,mantalingajanensis, , ,
Andreas Wistuba,AW-N_mant.02,mantalingajanensis, , ,
Andreas Wistuba,AW-N_mant.03,mantalingajanensis, , ,
Andreas Wistuba,AW-N_mant.04,mantalingajanensis, , ,
Andreas Wistuba,AW-N_mant.06,mantalingajanensis, , ,
Andreas Wistuba,AW-N_mant.07,mantalingajanensis, , ,
Andreas Wistuba,AW-N_mant.B,mantalingajanensis , , ,
Andreas Wistuba,AW-N_mant.F,mantalingajanensis , , ,
Andreas Wistuba,AW-N_map.01,mapuluensis, , ,
Andreas Wistuba,AW-N_map.02,mapuluensis, , ,
Andreas Wistuba,AW-N_map.03,mapuluensis, , ,
Andreas Wistuba,AW-N_map.04,mapuluensis, , ,
Andreas Wistuba,AW-N_map.05,mapuluensis, , ,
Andreas Wistuba,AW-N_map.06,mapuluensis, , ,
Andreas Wistuba,AW-N_map.07,mapuluensis, , ,
Andreas Wistuba,AW-N_map.08,mapuluensis, , ,
Andreas Wistuba,AW-N_map.09,mapuluensis, , ,
Andreas Wistuba,AW-N_map.10,mapuluensis, , ,
Andreas Wistuba,AW-N_maso.01,masoalensis , , ,
Andreas Wistuba,AW-N_micra.01,micramphora, , ,
Andreas Wistuba,AW-N_micra.02,micramphora, , ,
Andreas Wistuba,AW-N_micra.03,micramphora, , ,
Andreas Wistuba,AW-N_micra.04,micramphora, , ,
Andreas Wistuba,AW-N_micra.05,micramphora, , ,
Andreas Wistuba,AW-N_micra.06,micramphora, , ,
Andreas Wistuba,AW-N_micra.07,micramphora, , ,
Andreas Wistuba,AW-N_micra.08,micramphora, , ,
Andreas Wistuba,AW-N_mik.02,mikei, , ,
Andreas Wistuba,AW-N_mik.03,mikei, , ,
Andreas Wistuba,AW-N_moll_hrl_CP.01,mollis , , ,
Andreas Wistuba,AW-N_moll_hrl_CP.02,mollis , , ,
Andreas Wistuba,AW-N_mul.01,muluensis, , ,
Andreas Wistuba,AW-N_mur.01,murudensis , , ,
Andreas Wistuba,AW-N_nebu.02,nebularum , , ,
Andreas Wistuba,AW-N_nebu.03,nebularum , , ,
Andreas Wistuba,AW-N_nebu.04,nebularum , , ,
Andreas Wistuba,AW-N_nebu.05,nebularum , , ,
Andreas Wistuba,AW-N_nebu.06,nebularum , , ,
Andreas Wistuba,AW-N_north.01,northiana, , ,
Andreas Wistuba,AW-N_obl.RSC,oblanceolata, , ,
Andreas Wistuba,AW-N_obl.RC,oblanceolata , , ,
Andreas Wistuba,AW-N_ov.06,ovata , , ,
Andreas Wistuba,AW-N_ov.11,ovata , , ,
Andreas Wistuba,AW-N_ov.RC,ovata , , ,
Andreas Wistuba,AW-N_pal.06,palawanensis , , ,
Andreas Wistuba,AW-N_pal.08,palawanensis , , ,
Andreas Wistuba,AW-N_pal.09,palawanensis , , ,
Andreas Wistuba,AW-N_pal.RSC,palawanensis, , ,
Andreas Wistuba,AW-N_pant_Ga.01,pantaronensis, , ,
Andreas Wistuba,AW-N_pant_Ga.RC,pantaronensis, , ,
Andreas Wistuba,AW-N_pant_Sum.01,pantaronensis , , ,
Andreas Wistuba,AW-N_pant_Sum.RC,pantaronensis , , ,
Andreas Wistuba,AW-N_pelt.U2,peltata , , ,
Andreas Wistuba,AW-N_pelt.U3,peltata , , ,
Andreas Wistuba,AW-N_pelt.04,peltata , , ,
Andreas Wistuba,AW-N_pelt.6IP,peltata, , ,
Andreas Wistuba,AW-N_pelt.U7,peltata , , ,
Andreas Wistuba,AW-N_pelt.U9,peltata , , ,
Andreas Wistuba,AW-N_pelt.10IP,peltata , , ,
Andreas Wistuba,AW-N_perv_Cop.ISC,pervillei, , ,
Andreas Wistuba,AW-N_perv_TT.ISC,pervillei , , ,
Andreas Wistuba,AW-N_perv_TF.ISC,pervillei , , ,
Andreas Wistuba,AW-N_pito_SDL.01,pitopangii, , ,
Andreas Wistuba,AW-N_pito_SDL.RC,pitopangii, , ,
Andreas Wistuba,AW-N_plat.RSC,platychila , , ,
Andreas Wistuba,AW-N_plat.RC,platychila, , ,
Andreas Wistuba,AW-N_pulch.CS01,pulchra, , ,
Andreas Wistuba,AW-N_pulch.WR02,pulchra, , ,
Andreas Wistuba,AW-N_pulch.RC,pulchra, , ,
Andreas Wistuba,AW-N_raff_Beau.ISC,rafflesiana , , ,
Andreas Wistuba,AW-N_raj_kin.A01,rajah , , ,
Andreas Wistuba,AW-N_raj_kin.01,rajah, , ,
Andreas Wistuba,AW-N_raj_kin.02,rajah, , ,
Andreas Wistuba,AW-N_raj_kin.A03,rajah , , ,
Andreas Wistuba,AW-N_raj_kin.A05,rajah , , ,
Andreas Wistuba,AW-N_raj_kin.A06,rajah , , ,
Andreas Wistuba,AW-N_raj_kin.A09,rajah , , ,
Andreas Wistuba,AW-N_raj_kin.A10,rajah , , ,
Andreas Wistuba,AW-N_raj_kin.A08,rajah , , ,
Andreas Wistuba,AW-N_raj_kin.RSC,rajah , , ,
Andreas Wistuba,AW-N_raj_T.01,rajah, , ,
Andreas Wistuba,AW-N_raj_T.02,rajah, , ,
Andreas Wistuba,AW-N_raj_T.03,rajah, , ,
Andreas Wistuba,AW-N_raj_T.04,rajah, , ,
Andreas Wistuba,AW-N_raj_T.05,rajah, , ,
Andreas Wistuba,AW-N_raj_T.06,rajah, , ,
Andreas Wistuba,AW-N_raj_T.RSC,rajah , , ,
Andreas Wistuba,AW-N_rc.ISC,robcantleyi, , ,
Andreas Wistuba,AW-N_spat_ABG.01,spathulata, , ,
Andreas Wistuba,AW-N_sp_taw.ISC,spec. "Tawarensis" , , ,
Andreas Wistuba,AW-N_sp_taw.RSC,spec. "Tawarensis" , , ,
Andreas Wistuba,AW-N_sp_psk.01,spec. Pseudoklossii , , ,
Andreas Wistuba,AW-N_sp_psk.03,spec. Pseudoklossii , , ,
Andreas Wistuba,AW-N_sp_psk.Ho,spec. Pseudoklossii , , ,
Andreas Wistuba,AW-N_tlg.RSC,talangensis , , ,
Andreas Wistuba,AW-N_tom.05,tomoriana, , ,
Andreas Wistuba,AW-N_truncr.01,truncata, , ,
Andreas Wistuba,AW-N_trunc_MS.RSC,truncata , , ,
Andreas Wistuba,AW-N_trunc_MaMu.ISC,truncata , , ,
Andreas Wistuba,AW-N_undu.ISC,undulatifolia, , ,
Andreas Wistuba,AW-N_vei_Ray_low.01,veitchii , , ,
Andreas Wistuba,AW-N_vent_Porc.01,ventricosa , , ,
Andreas Wistuba,AW-N_vent_MA.01,ventricosa , , ,
Andreas Wistuba,AW-N_vent.01,ventricosa, , ,
Andreas Wistuba,AW-N_vieill.01,vieillardii , , ,
Andreas Wistuba,AW-N_vil.JG01,villosa, , ,
Andreas Wistuba,AW-N_vil.MT01,villosa, , ,
Andreas Wistuba,AW-N_vil.MT02,villosa, , ,
Andreas Wistuba,AW-N_vil.MT03,villosa, , ,
Andreas Wistuba,AW-N_vil.MT04,villosa, , ,
Andreas Wistuba,AW-N_virid.01,viridis, , ,
Andreas Wistuba,AW-N_virid.RC,viridis, , ,
Andreas Wistuba,AW-N_ad.03,adnata, , ,
Andreas Wistuba,AW-N_adrian.02,adrianii, , ,
Andreas Wistuba,AW-N_adrian.03,adrianii, , ,
Andreas Wistuba,AW-N_aenig.01,aenigma, , ,
Andreas Wistuba,AW-N_aenig.RC,aenigma, , ,
Andreas Wistuba,AW-N_alboBL.01,albomarginata , , ,
Andreas Wistuba,AW-N_alboBL.RC,albomarginata , , ,
Andreas Wistuba,AW-N_albor.01,albomarginata, , ,
Andreas Wistuba,AW-N_amp.RedStripes01,ampullaria , , ,
Andreas Wistuba,AW-N_amp.RC,ampullaria , , ,
Andreas Wistuba,AW-N_arist.ISC,aristolochioides, , ,
Andreas Wistuba,AW-N_arist.AC01,aristolochioides , , ,
Andreas Wistuba,AW-N_arist.AC02,aristolochioides , , ,
Andreas Wistuba,AW-N_arist.AC05,aristolochioides , , ,
Andreas Wistuba,AW-N_arist.NM03,aristolochioides , , ,
Andreas Wistuba,AW-N_arist.NM04,aristolochioides , , ,
Andreas Wistuba,AW-N_arist.NM06,aristolochioides , , ,
Andreas Wistuba,AW-N_arist.NM07,aristolochioides , , ,
Andreas Wistuba,AW-N_arist.RC,aristolochioides , , ,
Andreas Wistuba,AW-N_bosch_SKB.09,boschiana, , ,
Andreas Wistuba,AW-N_burb.01,burbidgeae, , ,
Andreas Wistuba,AW-N_burk.B,burkei , , ,
Andreas Wistuba,AW-N_burk.RC,burkei, , ,
Andreas Wistuba,AW-N_camp.01,campanulata , , ,
Andreas Wistuba,AW-N_camp.02,campanulata , , ,
Andreas Wistuba,AW-N_camp.08,campanulata , , ,
Andreas Wistuba,AW-N_camp.11(speckled),campanulata , , ,
Andreas Wistuba,AW-N_cec.RSC,ceciliae, , ,
Andreas Wistuba,AW-N_cec.RC,ceciliae , , ,
Andreas Wistuba,AW-N_clip.03N,clipeata , , ,
Andreas Wistuba,AW-N_clip.16-01,clipeata , , ,
Andreas Wistuba,AW-N_clip.16-02,clipeata , , ,
Andreas Wistuba,AW-N_clip.16-03,clipeata , , ,
Andreas Wistuba,AW-N_clip.U,clipeata , , ,
Andreas Wistuba,AW-N_cop.01,copelandii , , ,
Andreas Wistuba,AW-N_dans.J3,danseri , , ,
Andreas Wistuba,AW-N_dens.C,densiflora , , ,
Andreas Wistuba,AW-N_diat_98.07,diatas , , ,
Andreas Wistuba,AW-N_diat_98.MR,diatas , , ,
Andreas Wistuba,AW-dis.01,distillatoria, , ,
Andreas Wistuba,AW-N_ed_tb.01,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.02,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.03,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.04,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.05,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.06,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.07,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.08,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.09,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.10,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.11,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.12,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.13,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.14,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.15,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.16,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.17,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.18,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.19,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.20,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.21,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.ISC,edwardsiana , , ,
Andreas Wistuba,AW-N_ed_tb.22,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.23,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.24,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.25,edwardsiana, , ,
Andreas Wistuba,AW-N_ed_tb.102-1,edwardsiana , , ,
Andreas Wistuba,AW-N_ed_tb.102-2,edwardsiana , , ,
Andreas Wistuba,AW-Nx_Harr_Fx.01,edwardsiana , , ,
Andreas Wistuba,AW-N_eruc.RSC,erucoides, , ,
Andreas Wistuba,AW-N_eust_J.01,eustachya , , ,
Andreas Wistuba,AW-N_eust_J.RC,eustachya , , ,
Andreas Wistuba,AW-N_glab.01,glabrata, , ,
Andreas Wistuba,AW-N_glab.Langtrieb,glabrata , , ,
Andreas Wistuba,AW-N_glab.RC,glabrata, , ,
Andreas Wistuba,AW-N_al_GRP.01,graciliflora, , ,
Andreas Wistuba,AW-N_gym_S.01,gymnamphora, , ,
Andreas Wistuba,AW-N_gymJ.01,gymnamphora , , ,
Andreas Wistuba,AW-N_gymJ.Langtrieb,gymnamphora, , ,
Andreas Wistuba,AW-N_gymJ.RC,gymnamphora , , ,
Andreas Wistuba,AW-N_hamig.04,hamiguitanensis, , ,
Andreas Wistuba,AW-N_hamig.06,hamiguitanensis, , ,
Andreas Wistuba,AW-N_hamig.08,hamiguitanensis, , ,
Andreas Wistuba,AW-N_hamig.09,hamiguitanensis, , ,
Andreas Wistuba,AW-N_hamig.10,hamiguitanensis, , ,
Andreas Wistuba,AW-N_hems.01,hemsleyana, , ,
Andreas Wistuba,AW-N_hems.02,hemsleyana, , ,
Andreas Wistuba,AW-N_hems.03,hemsleyana, , ,
Andreas Wistuba,AW-N_hems.04,hemsleyana, , ,
Andreas Wistuba,AW-N_hisp_TG.01,hispida, , ,
Andreas Wistuba,AW-N_instay.RSC,insignis , , ,
Andreas Wistuba,AW-N_instay.RC,insignis, , ,
Andreas Wistuba,AW-N_kit.01,kitanglad, , ,
Andreas Wistuba,AW-N_kloss.01,klossii, , ,
Andreas Wistuba,AW-N_kloss.03,klossii, , ,
Andreas Wistuba,AW-N_kloss.05,klossii, , ,
Andreas Wistuba,AW-N_longpt.RSC,longiptera , , ,
Andreas Wistuba,AW-N_low_mur.01,lowii, , ,
Andreas Wistuba,AW-N_mvul.01,macrovulgaris , , ,
Andreas Wistuba,AW-N_mer.98/5,merrilliana, , ,
Andreas Wistuba,AW-mirsul.01,mirabilis , , ,
Andreas Wistuba,AW-N_echino.RSC,mirabilis, , ,
Andreas Wistuba,AW-N_nig_K.01,nigra, , ,
Andreas Wistuba,AW-N_perv_BB.ISC,pervillei , , ,
Andreas Wistuba,AW-N_pito_LL.01,pitopangii , , ,
Andreas Wistuba,AW-N_pito_LL.RC,pitopangii , , ,
Andreas Wistuba,AW-N_pulch_KB.01,pulchra , , ,
Andreas Wistuba,AW-N_pulch_KB.RC,pulchra , , ,
Andreas Wistuba,AW-N_raff_Bak_96.02,rafflesiana, , ,
Andreas Wistuba,AW-N_ram.MSr_01,ramispina, , ,
Andreas Wistuba,AW-N_ram.RC,ramispina, , ,
Andreas Wistuba,AW-N_ramos.TG01,ramos, , ,
Andreas Wistuba,AW-N_ramos.RC,ramos, , ,
Andreas Wistuba,AW-N_rein_rot.01,reinwardtiana , , ,
Andreas Wistuba,AW-N_rein_rot.Langtrieb,reinwardtiana , , ,
Andreas Wistuba,AW-N_reinSum.01,reinwardtiana , , ,
Andreas Wistuba,AW-N_rhomb_J.01,rhombicaulis, , ,
Andreas Wistuba,AW-N_rhomb_J.Langtrieb,rhombicaulis , , ,
Andreas Wistuba,AW-N_sib_MDR.13,sibuyanensis, , ,
Andreas Wistuba,AW-N_sing_A.01,singalana, , ,
Andreas Wistuba,AW-N_sp_Anip.01,spec Anipahan , , ,
Andreas Wistuba,AW-N_sp_Anip.02,spec Anipahan , , ,
Andreas Wistuba,AW-N_sp_Anip.03,spec Anipahan , , ,
Andreas Wistuba,AW-N_spect_BH.02,spectabilis, , ,
Andreas Wistuba,AW-N_spect_BH.05,spectabilis, , ,
Andreas Wistuba,AW-N_spect_BH.RC,spectabilis, , ,
Andreas Wistuba,AW-N_sum_Sipo.RSC,sumatrana , , ,
Andreas Wistuba,AW-N_tam.01,taminii , , ,
Andreas Wistuba,AW-N_tam.RC,taminii , , ,
Andreas Wistuba,AW-N_tenx.02,tenax, , ,
Andreas Wistuba,AW-N_tenx.RC,tenax, , ,
Andreas Wistuba,AW-N_tent_Ray.03,tentaculata, , ,
Andreas Wistuba,AW-N_ten_GE.01,tenuis , , ,
Andreas Wistuba,AW-N_ten_GE.02,tenuis , , ,
Andreas Wistuba,AW-N_ten_GE.RSC,tenuis, , ,
Andreas Wistuba,AW-N_ten_GE.RC,tenuis , , ,
Andreas Wistuba,AW-N_ulu.01,ulukaliana, , ,
Andreas Wistuba,AW-N_ulu.ISC,ulukaliana , , ,
Andreas Wistuba,AW-N_vei_high.07,veitchii , , ,
Andreas Wistuba,AW-N_vog.ISC,vogelii, , ,
Andreas Wistuba,AW-N_vog.TG01,vogelii , , ,
Andreas Wistuba,AW-N_vog.RC,vogelii , , ,
Andreas Wistuba,AW-N_zak_fusc_CR.03,zakriana, , ,
Andreas Wistuba,AW-N_zak_fusc_TR.05,zakriana, , ,
Floravitro,FV-001,glabrata, , ,Sulawesi
Floravitro,FV-001-01,glabrata, , ,Sulawesi
Floravitro,FV-002,vieillardii, , ,Blue River National Park
Floravitro,FV-002-01,vieillardii, , ,Blue River National Park
Floravitro,FV-003,truncata, , ,Mindanao
Floravitro,FV-003-01,truncata, , ,Mindanao
Floravitro,FV-004,peltata, , ,Mount Hamiguitan
Floravitro,FV-004-01,peltata, , ,Mount Hamiguitan
Floravitro,FV-005,sibuyanensis, , ,Mount Guiting-Guiting
Floravitro,FV-005-01,sibuyanensis, , ,Mount Guiting-Guiting
Floravitro,FV-007,bellii,Surigao del Norte
Floravitro,FV-007-01,bellii, , ,Surigao del Norte
Floravitro,FV-014,sanguinea, , ,Malaysia
Floravitro,FV-014-01,sanguinea, , ,Malaysia
Floravitro,FV-015,hirsuta, , ,Bako National Park
Floravitro,FV-015-01,hirsuta, , ,Bako National Park
Floravitro,FV-017,diatas, , ,Mount Bandahara
Floravitro,FV-017-01,diatas, , ,Mount Bandahara
Floravitro,FV-026,harauensis, , ,Harau Valley
Floravitro,FV-026-01,harauensis, , ,Harau Valley
Floravitro,FV-026-02,harauensis, , ,Harau Valley
Floravitro,FV-026-04,harauensis, , ,Harau Valley
Floravitro,FV-026-05,harauensis, , ,Harau Valley
Floravitro,FV-030,clipeata, , ,Mount Kelam
Floravitro,FV-030-01,clipeata,Male,Mount Kelam
Floravitro,FV-030-03,clipeata,Female,Mount Kelam
Floravitro,FV-030-04,clipeata,Female,Mount Kelam
Floravitro,FV-030-05,clipeata,Female,Mount Kelam
Floravitro,FV-030-07,clipeata,Female,Mount Kelam
Floravitro,FV-030-09,clipeata,Female,Mount Kelam
Floravitro,FV-030-10,clipeata,Male,Mount Kelam
Floravitro,FV-030-11,clipeata,Female,Mount Kelam
Floravitro,FV-030-12,clipeata,Female,Mount Kelam
Floravitro,FV-030-13,clipeata,Male,Mount Kelam
Floravitro,FV-030-16,clipeata,Female,Mount Kelam
Floravitro,FV-030-17,clipeata,Female,Mount Kelam
Floravitro,FV-033,singalana, ,Mount Kunyit
Floravitro,FV-033-01,singalana, ,Mount Kunyit
Floravitro,FV-034,albomarginata, ,Penang Island
Floravitro,FV-034-01,albomarginata, ,Penang Island
Floravitro,FV-036,palawanensis, ,Sultan Peak
Floravitro,FV-036-01,palawanensis, ,Sultan Peak
Floravitro,FV-037,alba, ,Mount Tahan
Floravitro,FV-037-01,alba, ,Mount Tahan
Floravitro,FV-040,sumatrana, ,Sibolga
Floravitro,FV-040-ISC, ,sumatrana
Floravitro,FV-041,ephippiata, ,Hose Mountains
Floravitro,FV-041-01,ephippiata, ,Hose Mountains
Floravitro,FV-043,khasiana, ,Khasi Hills
Floravitro,FV-043-ISC, ,khasiana,Meghalaya
Floravitro,FV-044,sp. Papua, ,Mount Doorman
Floravitro,FV-044-01,sp. Papua, ,Mount Doorman
Floravitro,FV-045,clipeata, ,Mount Kelam
Floravitro,FV-045-01,clipeata,Female, ,Mount Kelam
Floravitro,FV-045-02,clipeata,Female, ,Mount Kelam
Floravitro,FV-046,clipeata, ,Mount Kelam
Floravitro,FV-046-ISC,clipeata, ,Mount Kelam
Floravitro,FV-049,pervillei, ,Mount Copolia
Floravitro,FV-049-01,pervillei, ,Mount Copolia
Floravitro,FV-049-02,pervillei, ,Mount Copolia
Floravitro,FV-049-03,pervillei, ,Mount Copolia
Floravitro,FV-049-04,pervillei, ,Mount Copolia
Floravitro,FV-049-06,pervillei, ,Mount Copolia
Floravitro,FV-049-08,pervillei, ,Mount Copolia
Floravitro,FV-049-13,pervillei, ,Mount Copolia
Floravitro,FV-049-14,pervillei, ,Mount Copolia
Floravitro,FV-049-15,pervillei, ,Mount Copolia
Floravitro,FV-050,pervillei, ,Mount Trois Frères
Floravitro,FV-050-01,pervillei, ,Mount Trois Frères
Floravitro,FV-050-02,pervillei, ,Mount Trois Frères
Floravitro,FV-050-04,pervillei, ,Mount Trois Frères
Floravitro,FV-050-05,pervillei, ,Mount Trois Frères
Floravitro,FV-050-06,pervillei, ,Mount Trois Frères
Floravitro,FV-050-07,pervillei, ,Mount Trois Frères
Floravitro,FV-050-08,pervillei, ,Mount Trois Frères
Floravitro,FV-050-12,pervillei, ,Mount Trois Frères
Floravitro,FV-050-13,pervillei, ,Mount Trois Frères
Floravitro,FV-050-19,pervillei, ,Mount Trois Frères
Floravitro,FV-052,truncata, ,Mindanao
Floravitro,FV-052-ISC,truncata, ,Mindanao
Floravitro,FV-061,edwardsiana, ,Marai Parai
Floravitro,FV-061-01,edwardsiana, ,Marai Parai
Floravitro,FV-061-02,edwardsiana, ,Marai Parai
Floravitro,FV-061-03,edwardsiana, ,Marai Parai
Floravitro,FV-061-04,edwardsiana, ,Marai Parai
Floravitro,FV-061-05,edwardsiana, ,Marai Parai
Floravitro,FV-061-06,edwardsiana, ,Marai Parai
Floravitro,FV-061-07,edwardsiana, ,Marai Parai
Floravitro,FV-061-08,edwardsiana, ,Marai Parai
Floravitro,FV-061-09,edwardsiana, ,Marai Parai
Floravitro,FV-061-10,edwardsiana, ,Marai Parai
Floravitro,FV-061-11,edwardsiana, ,Marai Parai
Floravitro,FV-061-13,edwardsiana, ,Marai Parai
Floravitro,FV-061-14,edwardsiana, ,Marai Parai
Floravitro,FV-061-15,edwardsiana, ,Marai Parai
Floravitro,FV-061-17,edwardsiana, ,Marai Parai
Floravitro,FV-061-18,edwardsiana, ,Marai Parai
Floravitro,FV-061-19,edwardsiana, ,Marai Parai
Floravitro,FV-066,bokorensis, ,Mount Bokor
Floravitro,FV-066-06,bokorensis, ,Mount Bokor
Floravitro,FV-066-13,bokorensis, ,Mount Bokor
Floravitro,FV-066-16,bokorensis, ,Mount Bokor
Floravitro,FV-091,mapuluensis, ,Tabalar Mountains
Floravitro,FV-091-ISC,mapuluensis, ,Tabalar Mountains
Floravitro,FV-091-08,mapuluensis, ,Tabalar Mountains
Floravitro,FV-091-09,mapuluensis, ,Tabalar Mountains
Floravitro,FV-091-16,mapuluensis, ,Tabalar Mountains
Floravitro,FV-091-18,mapuluensis, ,Tabalar Mountains
Floravitro,FV-092,longiptera, ,Dairi Regency
Floravitro,FV-092-ISC,longiptera, ,Dairi Regency
Floravitro,FV-098,truncata, ,Mindanao
Floravitro,FV-098-01,truncata, ,Mindanao
Floravitro,FV-115,stenophylla, ,Mamut Mine
Floravitro,FV-115-ISC,stenophylla, ,Mamut Mine
Floravitro,FV-126,villosa, ,Mount Kinabalu
Floravitro,FV-126-ISC,villosa, ,Mount Kinabalu
Floravitro,FV-133,kongkandana, ,Songkhla Province
Floravitro,FV-133-ISC,kongkandana, ,Songkhla Province
Floravitro,FV-134,andamana, ,Phag Nga Province
Floravitro,FV-134-ISC,andamana, ,Phag Nga Province
Floravitro,FV-144,suratensis, ,Surat Thani
