openapi: 3.0.0
tags:
  - name: Growlistmanagement
    description: Operations to add/remove Plants to the Useraccount
info:
  title: Nepflow User
  description: |-
    API for Growlist Operations
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:4200/api
paths:
  /growlist/nepenthes:
    get:
      summary: get all nepenthes of currently logged in User
      tags:
        - Growlistmanagement
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GrowlistDTO'
        '404':
          description: User not found
    post:
      summary: Add Clone of a Nepenthes to currently logged in User
      tags:
        - Growlistmanagement
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CloneDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloneDTO'
        '500':
          description: Error, could not add Specimen to user

  /growlist/nepenthes/{specimenId}:
    delete:
      parameters:
        - in: path
          name: specimenId
          schema:
            type: string
          required: true

      summary: remove a clone from the growlisti If the removed plant was already used for a trade it will be a soft delete in the relation part
      tags:
        - Growlistmanagement
      responses:
        '200':
          description: OK
        '500':
          description: Error, could not add Nepenthes Clone to user
    put:
      parameters:
        - in: path
          name: specimenId
          schema:
            type: string
          required: true
      summary: update values
      tags:
        - Growlistmanagement
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CloneDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloneDTO'
        '500':
          description: Could not update Specimen

  /growlist/{user}/nepenthes:
    get:
      summary: get Nepenthes of a specific User
      tags:
        - Growlistmanagement
      parameters:
        - in: path
          name: user
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GrowlistDTO'

        '404':
          description: Error, User not found



components:



  schemas:

    LocationDTO:
      type: string

    ProducerDTO:
      type: string

    LabelDTO:
      type: object
      properties:
        name:
          type: string
        prefix:
          type: string


    CloneDTO:
      type: object
      properties:
        cloneId:
          type: string
        internalcloneId:
          type: string
        sex:
          type: string
        localName:
          description: localName allows user to set a name, to distinguish easier same clones
          type: string
        imageURL:
          type: string
        grex:
          $ref: '#/components/schemas/CloneGrexDTO'
        producer:
          $ref: '#/components/schemas/ProducerDTO'
        Location:
          $ref: '#/components/schemas/LocationDTO'



    CloneGrexDTO:
      type: object
      properties:
        cloneId:
          type: string
        father:
          $ref: '#/components/schemas/CloneDTO'
        mother:
          $ref: '#/components/schemas/CloneDTO'



    GrowlistDTO:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        specimens:
          type: array
          items:
            $ref: '#/components/schemas/CloneDTO'






