openapi: 3.0.0
tags:
  - name: Usermanagement
    description: Operations to manage and retrive Users
info:
  title: Nepflow User
  description: |-
    API for User Operations
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:4200/api
paths:
  /user:
    get:
      summary: return current User.
      tags:
        - Usermanagement
      responses:
        '200':
          description: User exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '404':
          description: User not found
    post:
      summary: Create an User in the Application with minimal sensitive Information.
      tags:
        - Usermanagement
      requestBody:
        description: empty body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'

      responses:
        '201':
          description: Profile created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '204':
          description: Error
    put:
      summary: Update Information of User
      tags:
        - Usermanagement
      requestBody:
        description: User DTO with all changeable values
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '201':
          description: Profile change successfully.
        '204':
          description: Error

  /users:
    get:
      summary: get all Users
      tags:
        - Usermanagement
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserPrivacyDTO'
        '404':
          description: No Information found for User
  /users/{username}:
    get:
      summary: get Userinformation
      tags:
        - Usermanagement
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPrivacyDTO'
        '404':
          description: No Information found for User
components:
  schemas:
    UserPrivacyDTO:
      type: object
      properties:
        username:
          type: string
        country:
          type: string

    UserDTO:
      type: object
      properties:
        username:
          type: string
        contactInformation:
          type: string
        country:
          type: string
