openapi: 3.0.0
tags:
  - name: chat
    description: Operations for the chat

info:
  title: Nepflow Chat
  description: |-
    API for Chat Operations
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/api

paths:
  /chats/:
    parameters:
      - in: query
        name: pageable
        required: true
        schema:
          $ref: '#/components/schemas/Pageable'

    get:
      summary: get a summary of Chats from the currently logged in User
      tags:
        - chat
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/ChatSummaryDTO'
  /chats/{chatId}:
    parameters:
      - $ref: "#/components/parameters/chatId"
    get:
      parameters:
        - in: query
          name: pageable
          required: true
          schema:
            $ref: '#/components/schemas/Pageable'

      summary: get one Chat and it´s messages
      tags:
        - chat
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatDTO'
    post:
      summary: add a Message to a Chat
      tags:
        - chat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewMessageDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewMessageDTO'






components:
  parameters:

    chatId:
      name: chatId
      in: path
      required: true
      schema:
        type: integer
        format: int32

  schemas:
    ChatSummaryDTO:
      type: object
      description: "Represents a Summary of Chatrooms depending on the latest Message."
      properties:
        chats:
          type: array
          items:
            $ref: "#/components/schemas/ChatDTO"
        totalPages:
          type: integer


    ChatDTO:
      type: object
      description: "Represents a Chatroom with the 50 newest Messages"
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        user1:
          $ref: "#/components/schemas/ChatUserDTO"
        user2:
          $ref: "#/components/schemas/ChatUserDTO"
        messages:
          type: array
          items:
            $ref: "#/components/schemas/MessageDTO"


    MessageDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        content:
          type: string
        timestamp:
          type: string
          format: date-time
        sender:
          $ref: "#/components/schemas/ChatUserDTO"


    ChatUserDTO:
      type: object
      properties:
        username:
          type: string


    NewMessageDTO:
      type: object
      properties:
        content:
          type: string
        timestamp:
          type: string
          format: date-time

    Pageable:
      description: minimal Pageable query parameters
      type: object
      properties:
        page:
          type: integer
          format: int32
          default: 0
        size:
          type: integer
          format: int32
          default: 20










