openapi: 3.0.0
tags:
  - name: User
    description: Operations to manage User
info:
  title: Nepflow User
  description: |-
    API for User Operations
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:4200/api
paths:
  /user:
    post:
      summary: Create an User in the Application with minimal sensitive Information.
      tags:
        - User
      requestBody:
        description: empty body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'

      responses:
        '201':
          description: Profile created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '204':
          description: Error
    put:
      summary: Update Information of User
      tags:
        - User
      requestBody:
        description: User DTO with all changeable values
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '201':
          description: Profile changed successfully.
        '204':
          description: Error
    get:
      summary: get Userinformation
      tags:
        - User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '404':
          description: No Information found for User

components:
  schemas:
    UserDTO:
      type: object
      properties:
        email:
          type: string
        username:
          type: string
        password:
          type: string
        contactInformation:
          type: string
        region:
          type: string
          description: Region like EU or USA
