/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.nepflow.NepenthesManagement.Controller;

import com.nepflow.NepenthesManagement.Dto.CloneDTO;
import com.nepflow.NepenthesManagement.Dto.HybridCloneDTO;
import com.nepflow.NepenthesManagement.Dto.LabelClonesDTO;
import com.nepflow.NepenthesManagement.Dto.LabelDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-05-31T22:42:44.669728600+02:00[Europe/Berlin]")
@Validated
@Tag(name = "NepenthesManagement", description = "Operations to manage Nepenthes")
public interface NepenthesManagementApi {

    default NepenthesManagementApiDelegate getDelegate() {
        return new NepenthesManagementApiDelegate() {};
    }

    /**
     * GET /clone/multi-hybrid/ : get all multi-hybrid Clones
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "cloneMultiHybridGet",
        summary = "get all multi-hybrid Clones",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = HybridCloneDTO.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/clone/multi-hybrid/",
        produces = { "application/json" }
    )
    default ResponseEntity<List<HybridCloneDTO>> cloneMultiHybridGet(
        
    ) {
        return getDelegate().cloneMultiHybridGet();
    }


    /**
     * GET /clone/multi-hybrid/ic : get all multi-hybrid IC Clones
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "cloneMultiHybridIcGet",
        summary = "get all multi-hybrid IC Clones",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = HybridCloneDTO.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/clone/multi-hybrid/ic",
        produces = { "application/json" }
    )
    default ResponseEntity<List<HybridCloneDTO>> cloneMultiHybridIcGet(
        
    ) {
        return getDelegate().cloneMultiHybridIcGet();
    }


    /**
     * POST /clone/multi-hybrid/ic : add a new iv multi-hybrid clone
     *
     * @param hybridCloneDTO  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "cloneMultiHybridIcPost",
        summary = "add a new iv multi-hybrid clone",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = HybridCloneDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/clone/multi-hybrid/ic",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<HybridCloneDTO> cloneMultiHybridIcPost(
        @Parameter(name = "HybridCloneDTO", description = "", required = true) @Valid @RequestBody HybridCloneDTO hybridCloneDTO
    ) {
        return getDelegate().cloneMultiHybridIcPost(hybridCloneDTO);
    }


    /**
     * PUT /clone/multi-hybrid/ic
     *
     * @param hybridCloneDTO  (required)
     * @return OK (status code 200)
     *         or No nepenthes found (status code 404)
     */
    @Operation(
        operationId = "cloneMultiHybridIcPut",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = HybridCloneDTO.class))
            }),
            @ApiResponse(responseCode = "404", description = "No nepenthes found")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/clone/multi-hybrid/ic",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<HybridCloneDTO> cloneMultiHybridIcPut(
        @Parameter(name = "HybridCloneDTO", description = "", required = true) @Valid @RequestBody HybridCloneDTO hybridCloneDTO
    ) {
        return getDelegate().cloneMultiHybridIcPut(hybridCloneDTO);
    }


    /**
     * GET /clone/multi-hybrid/iv : get all multi-hybrid IV Clones
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "cloneMultiHybridIvGet",
        summary = "get all multi-hybrid IV Clones",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = HybridCloneDTO.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/clone/multi-hybrid/iv",
        produces = { "application/json" }
    )
    default ResponseEntity<List<HybridCloneDTO>> cloneMultiHybridIvGet(
        
    ) {
        return getDelegate().cloneMultiHybridIvGet();
    }


    /**
     * POST /clone/multi-hybrid/iv : add a new iv multi-hybrid
     *
     * @param hybridCloneDTO  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "cloneMultiHybridIvPost",
        summary = "add a new iv multi-hybrid",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = HybridCloneDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/clone/multi-hybrid/iv",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<HybridCloneDTO> cloneMultiHybridIvPost(
        @Parameter(name = "HybridCloneDTO", description = "", required = true) @Valid @RequestBody HybridCloneDTO hybridCloneDTO
    ) {
        return getDelegate().cloneMultiHybridIvPost(hybridCloneDTO);
    }


    /**
     * PUT /clone/multi-hybrid/iv
     *
     * @param hybridCloneDTO  (required)
     * @return OK (status code 200)
     *         or No nepenthes found (status code 404)
     */
    @Operation(
        operationId = "cloneMultiHybridIvPut",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = HybridCloneDTO.class))
            }),
            @ApiResponse(responseCode = "404", description = "No nepenthes found")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/clone/multi-hybrid/iv",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<HybridCloneDTO> cloneMultiHybridIvPut(
        @Parameter(name = "HybridCloneDTO", description = "", required = true) @Valid @RequestBody HybridCloneDTO hybridCloneDTO
    ) {
        return getDelegate().cloneMultiHybridIvPut(hybridCloneDTO);
    }


    /**
     * GET /clone/primary-hybrids/ : get all hybrid Clones
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "clonePrimaryHybridsGet",
        summary = "get all hybrid Clones",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = HybridCloneDTO.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/clone/primary-hybrids/",
        produces = { "application/json" }
    )
    default ResponseEntity<List<HybridCloneDTO>> clonePrimaryHybridsGet(
        
    ) {
        return getDelegate().clonePrimaryHybridsGet();
    }


    /**
     * GET /clone/primary-hybrids/ic : get all IC Hybrids
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "clonePrimaryHybridsIcGet",
        summary = "get all IC Hybrids",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = HybridCloneDTO.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/clone/primary-hybrids/ic",
        produces = { "application/json" }
    )
    default ResponseEntity<List<HybridCloneDTO>> clonePrimaryHybridsIcGet(
        
    ) {
        return getDelegate().clonePrimaryHybridsIcGet();
    }


    /**
     * POST /clone/primary-hybrids/ic : add a new iv hybrid clone
     *
     * @param hybridCloneDTO  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "clonePrimaryHybridsIcPost",
        summary = "add a new iv hybrid clone",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = HybridCloneDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/clone/primary-hybrids/ic",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<HybridCloneDTO> clonePrimaryHybridsIcPost(
        @Parameter(name = "HybridCloneDTO", description = "", required = true) @Valid @RequestBody HybridCloneDTO hybridCloneDTO
    ) {
        return getDelegate().clonePrimaryHybridsIcPost(hybridCloneDTO);
    }


    /**
     * PUT /clone/primary-hybrids/ic
     *
     * @param hybridCloneDTO  (required)
     * @return OK (status code 200)
     *         or No nepenthes found (status code 404)
     */
    @Operation(
        operationId = "clonePrimaryHybridsIcPut",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = HybridCloneDTO.class))
            }),
            @ApiResponse(responseCode = "404", description = "No nepenthes found")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/clone/primary-hybrids/ic",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<HybridCloneDTO> clonePrimaryHybridsIcPut(
        @Parameter(name = "HybridCloneDTO", description = "", required = true) @Valid @RequestBody HybridCloneDTO hybridCloneDTO
    ) {
        return getDelegate().clonePrimaryHybridsIcPut(hybridCloneDTO);
    }


    /**
     * GET /clone/primary-hybrids/iv : get all IV Hybrids
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "clonePrimaryHybridsIvGet",
        summary = "get all IV Hybrids",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = HybridCloneDTO.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/clone/primary-hybrids/iv",
        produces = { "application/json" }
    )
    default ResponseEntity<List<HybridCloneDTO>> clonePrimaryHybridsIvGet(
        
    ) {
        return getDelegate().clonePrimaryHybridsIvGet();
    }


    /**
     * POST /clone/primary-hybrids/iv : add a new iv hybrid
     *
     * @param hybridCloneDTO  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "clonePrimaryHybridsIvPost",
        summary = "add a new iv hybrid",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = HybridCloneDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/clone/primary-hybrids/iv",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<HybridCloneDTO> clonePrimaryHybridsIvPost(
        @Parameter(name = "HybridCloneDTO", description = "", required = true) @Valid @RequestBody HybridCloneDTO hybridCloneDTO
    ) {
        return getDelegate().clonePrimaryHybridsIvPost(hybridCloneDTO);
    }


    /**
     * PUT /clone/primary-hybrids/iv
     *
     * @param hybridCloneDTO  (required)
     * @return OK (status code 200)
     *         or No nepenthes found (status code 404)
     */
    @Operation(
        operationId = "clonePrimaryHybridsIvPut",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = HybridCloneDTO.class))
            }),
            @ApiResponse(responseCode = "404", description = "No nepenthes found")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/clone/primary-hybrids/iv",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<HybridCloneDTO> clonePrimaryHybridsIvPut(
        @Parameter(name = "HybridCloneDTO", description = "", required = true) @Valid @RequestBody HybridCloneDTO hybridCloneDTO
    ) {
        return getDelegate().clonePrimaryHybridsIvPut(hybridCloneDTO);
    }


    /**
     * GET /clone/species/ : get all Species Clones
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "cloneSpeciesGet",
        summary = "get all Species Clones",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = CloneDTO.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/clone/species/",
        produces = { "application/json" }
    )
    default ResponseEntity<List<CloneDTO>> cloneSpeciesGet(
        
    ) {
        return getDelegate().cloneSpeciesGet();
    }


    /**
     * GET /clone/species/ic : get all IV Species Clones
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "cloneSpeciesIcGet",
        summary = "get all IV Species Clones",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = CloneDTO.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/clone/species/ic",
        produces = { "application/json" }
    )
    default ResponseEntity<List<CloneDTO>> cloneSpeciesIcGet(
        
    ) {
        return getDelegate().cloneSpeciesIcGet();
    }


    /**
     * POST /clone/species/ic : add a new iv clone of a nepenthes
     *
     * @param cloneDTO Clone DTO with new values (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "cloneSpeciesIcPost",
        summary = "add a new iv clone of a nepenthes",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CloneDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/clone/species/ic",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CloneDTO> cloneSpeciesIcPost(
        @Parameter(name = "CloneDTO", description = "Clone DTO with new values", required = true) @Valid @RequestBody CloneDTO cloneDTO
    ) {
        return getDelegate().cloneSpeciesIcPost(cloneDTO);
    }


    /**
     * PUT /clone/species/ic
     *
     * @param cloneDTO  (required)
     * @return OK (status code 200)
     *         or No nepenthes found (status code 404)
     */
    @Operation(
        operationId = "cloneSpeciesIcPut",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CloneDTO.class))
            }),
            @ApiResponse(responseCode = "404", description = "No nepenthes found")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/clone/species/ic",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CloneDTO> cloneSpeciesIcPut(
        @Parameter(name = "CloneDTO", description = "", required = true) @Valid @RequestBody CloneDTO cloneDTO
    ) {
        return getDelegate().cloneSpeciesIcPut(cloneDTO);
    }


    /**
     * GET /clone/species/iv : get all IV Species Clones
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "cloneSpeciesIvGet",
        summary = "get all IV Species Clones",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = CloneDTO.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/clone/species/iv",
        produces = { "application/json" }
    )
    default ResponseEntity<List<CloneDTO>> cloneSpeciesIvGet(
        
    ) {
        return getDelegate().cloneSpeciesIvGet();
    }


    /**
     * POST /clone/species/iv : add a new iv clone of a nepenthes
     *
     * @param cloneDTO Clone DTO with new values (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "cloneSpeciesIvPost",
        summary = "add a new iv clone of a nepenthes",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CloneDTO.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/clone/species/iv",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CloneDTO> cloneSpeciesIvPost(
        @Parameter(name = "CloneDTO", description = "Clone DTO with new values", required = true) @Valid @RequestBody CloneDTO cloneDTO
    ) {
        return getDelegate().cloneSpeciesIvPost(cloneDTO);
    }


    /**
     * PUT /clone/species/iv
     *
     * @param cloneDTO  (required)
     * @return OK (status code 200)
     *         or No nepenthes found (status code 404)
     */
    @Operation(
        operationId = "cloneSpeciesIvPut",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CloneDTO.class))
            }),
            @ApiResponse(responseCode = "404", description = "No nepenthes found")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/clone/species/iv",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CloneDTO> cloneSpeciesIvPut(
        @Parameter(name = "CloneDTO", description = "", required = true) @Valid @RequestBody CloneDTO cloneDTO
    ) {
        return getDelegate().cloneSpeciesIvPut(cloneDTO);
    }


    /**
     * POST /location : add a new Location
     *
     * @param body LocationdTo with all necessary Attributes (required)
     * @return OK (status code 200)
     *         or Internal Error (status code 500)
     */
    @Operation(
        operationId = "locationPost",
        summary = "add a new Location",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = String.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Error")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/location",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<String> locationPost(
        @Parameter(name = "body", description = "LocationdTo with all necessary Attributes", required = true) @Valid @RequestBody String body
    ) {
        return getDelegate().locationPost(body);
    }


    /**
     * GET /nepenthes : get all nepenthes
     *
     * @return OK (status code 200)
     *         or No nepenthes found (status code 404)
     */
    @Operation(
        operationId = "nepenthesGet",
        summary = "get all nepenthes",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = LabelDTO.class)))
            }),
            @ApiResponse(responseCode = "404", description = "No nepenthes found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/nepenthes",
        produces = { "application/json" }
    )
    default ResponseEntity<List<LabelDTO>> nepenthesGet(
        
    ) {
        return getDelegate().nepenthesGet();
    }


    /**
     * GET /nepenthes/{name}/{clone} : get s specific clone
     *
     * @param name  (required)
     * @param clone  (required)
     * @return OK (status code 200)
     *         or Clone does not exist (status code 404)
     */
    @Operation(
        operationId = "nepenthesNameCloneGet",
        summary = "get s specific clone",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CloneDTO.class))
            }),
            @ApiResponse(responseCode = "404", description = "Clone does not exist")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/nepenthes/{name}/{clone}",
        produces = { "application/json" }
    )
    default ResponseEntity<CloneDTO> nepenthesNameCloneGet(
        @Parameter(name = "name", description = "", required = true, in = ParameterIn.PATH) @PathVariable("name") String name,
        @Parameter(name = "clone", description = "", required = true, in = ParameterIn.PATH) @PathVariable("clone") String clone
    ) {
        return getDelegate().nepenthesNameCloneGet(name, clone);
    }


    /**
     * GET /nepenthes/{name} : get a nepenthes and their clones
     *
     * @param name  (required)
     * @return OK (status code 200)
     *         or nepenthes not found (status code 404)
     */
    @Operation(
        operationId = "nepenthesNameGet",
        summary = "get a nepenthes and their clones",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LabelClonesDTO.class))
            }),
            @ApiResponse(responseCode = "404", description = "nepenthes not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/nepenthes/{name}",
        produces = { "application/json" }
    )
    default ResponseEntity<LabelClonesDTO> nepenthesNameGet(
        @Parameter(name = "name", description = "", required = true, in = ParameterIn.PATH) @PathVariable("name") String name
    ) {
        return getDelegate().nepenthesNameGet(name);
    }


    /**
     * POST /nepenthes : Create new nepenthes
     *
     * @param labelDTO  (required)
     * @return OK (status code 200)
     *         or No nepenthes found (status code 404)
     */
    @Operation(
        operationId = "nepenthesPost",
        summary = "Create new nepenthes",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LabelDTO.class))
            }),
            @ApiResponse(responseCode = "404", description = "No nepenthes found")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/nepenthes",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<LabelDTO> nepenthesPost(
        @Parameter(name = "LabelDTO", description = "", required = true) @Valid @RequestBody LabelDTO labelDTO
    ) {
        return getDelegate().nepenthesPost(labelDTO);
    }


    /**
     * POST /producer : add a new Producer
     *
     * @param body DTO with all necessary Attributes (required)
     * @return OK (status code 200)
     *         or Internal Error (status code 500)
     */
    @Operation(
        operationId = "producerPost",
        summary = "add a new Producer",
        tags = { "NepenthesManagement" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = String.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Error")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/producer",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<String> producerPost(
        @Parameter(name = "body", description = "DTO with all necessary Attributes", required = true) @Valid @RequestBody String body
    ) {
        return getDelegate().producerPost(body);
    }

}
