openapi: 3.0.0
tags:
  - name: nepenthes
    description: Operations to manage Nepenthes
  - name: NepenthesMetadata
    description: not sure if actually necessary for now
  - name: Growlistmanagement
    description: Operations for the GrowlistManagement of an user

info:
  title: Nepflow Nepenthes
  description: |-
    API for Nepenthes Operations
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/api

paths:
  /producer:
    post:
      summary: add a new Producer
      tags:
        - NepenthesMetadata
      requestBody:
        description: DTO with all necessary Attributes
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProducerDTO'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProducerDTO'
        '500':
          description: Internal Error
  /clone/{nepenthesType}:
    parameters:
      - $ref: "#/components/parameters/nepenthesType"
    get:
      summary: get all Nepenthes of a specific Nepenthestype
      tags:
        - nepenthes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/LabelDTO'
  /clone/{nepenthesType}/{name}:
    parameters:
      - $ref: "#/components/parameters/nepenthesType"
      - $ref: "#/components/parameters/name"

    get:
      summary: get all clones of a Nepenthes
      tags:
        - nepenthes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'

  /clone/{nepenthesType}/{cloneType}/{name}:
    parameters:
      - $ref: "#/components/parameters/nepenthesType"
      - $ref: "#/components/parameters/cloneType"
      - $ref: "#/components/parameters/name"

    get:
      summary: get either iv or ic clones of a Nepenthes
      tags:
        - nepenthes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'

    post:
      summary: add a new clone to a nepenthes
      tags:
        - nepenthes
      requestBody:
        description: Clone DTO with new values
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelCloneDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelCloneDTO'

  /clone/{nepenthesType}/{cloneType}/{name}/{internalCloneId}:
    parameters:
      - $ref: "#/components/parameters/nepenthesType"
      - $ref: "#/components/parameters/cloneType"
      - $ref: "#/components/parameters/name"
      - $ref: "#/components/parameters/internalCloneId"

    put:
      summary: update a Clone
      tags:
        - nepenthes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelCloneDTO'

  /growlist/{growlistId}/public:
    patch:
      parameters:
        - $ref: "#/components/parameters/growlistId"

      summary: set Growlist to public or private
      tags:
        - Growlistmanagement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GrowlistPublic'
      responses:
        '200':
          description: OK




  /growlist/clone/add/{internalCloneId}:
    parameters:
      - $ref: "#/components/parameters/internalCloneId"
    post:
      summary: Add an existing Clone of a Nepenthes to the Growlist.
      tags:
        - Growlistmanagement
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpecimenCloneDTO'
        '500':
          description: Error, could not add Specimen to user

  /growlist/create/clone/{cloneType}:
    parameters:
      - $ref: "#/components/parameters/cloneType"
    post:
      summary: Create a new IV or IC Clone and Add it to the Growlist
      tags:
        - Growlistmanagement
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelCloneDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpecimenCloneDTO'
        '500':
          description: Error, could not add Specimen to user
  /growlist/create/nepenthes/{cloneType}:
    parameters:
      - $ref: "#/components/parameters/cloneType"
    post:
      summary: Create a new Nepenthes and an additional IV or IC Clone and Add it to the Growlist
      tags:
        - Growlistmanagement
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelCloneDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpecimenCloneDTO'
        '500':
          description: Error, could not add Specimen to user
  /specimens/{specimenId}:
    parameters:
      - $ref: "#/components/parameters/specimenId"
    delete:
      summary: remove a specimen from the growlistist. If the removed plant was already used for a trade, only a soft delete will happen
      tags:
        - Growlistmanagement
      responses:
        '200':
          description: OK
        '500':
          description: Error, could not add Nepenthes Clone to user
    get:
      tags:
        - Growlistmanagement
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpecimenCloneDTO'
  /specimens/{specimenId}/sex:
    parameters:
      - $ref: "#/components/parameters/specimenId"
    patch:
      summary: Update Sex of a specific Specimen, only works if Specimes current sex is unkown
      tags:
        - Growlistmanagement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpecimenUpdateSex'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpecimenUpdateSex'

        '500':
          description: Error, could not update Specimen Sex

  /specimens/{specimenId}/flowering:
    parameters:
      - $ref: "#/components/parameters/specimenId"

    patch:
      summary: Update the flowering status of a clone
      tags:
        - Growlistmanagement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpecimenUpdateFlowerStatus'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpecimenUpdateFlowerStatus'

        '500':
          description: Error, could not update flowering status


  /specimens/{specimenId}/image:
    parameters:
      - $ref: "#/components/parameters/specimenId"
    put:
      summary: update Image
      tags:
        - Growlistmanagement
      requestBody:
        required: false
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SpecimenUpdateImage'
      responses:
        '200':
          description: OK
        '500':
          description: Could not update Specimen





  /growlist/{username}/clones:
    parameters:
      - $ref: "#/components/parameters/username"

    get:
      summary: get all Specimens of a specific User, if Growlist is public
      tags:
        - Growlistmanagement
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GrowlistDTO'

        '404':
          description: Error, User not found




components:

  parameters:
    nepenthesType:
      name: nepenthesType
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/NepenthesType'
    cloneType:
      name: cloneType
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/CloneType'
    name:
      name: name
      in: path
      required: true
      schema:
        type: string

    internalCloneId:
      name: internalCloneId
      in: path
      required: true
      schema:
        type: string

    username:
      name: username
      in: path
      required: true
      schema:
        type: string

    specimenId:
      name: specimenId
      in: path
      required: true
      schema:
        type: string

    growlistId:
      name: growlistId
      in: path
      required: true
      schema:
        type: string


  schemas:

    ProducerDTO:
      type: object
      properties:
        name:
          type: string
        contact:
          type: string

    # abstraction of Hybrid/Nepenthes etc.
    LabelDTO:
      type: object
      properties:
        nepenthesName:
          type: string
        prefix:
          type: string


    CloneDTO:
      type: object
      properties:
        nepenthesName:
          type: string
        cloneId:
          type: string
        internalCloneId:
          type: string
        sex:
          type: string
        description:
          type: string
        nickname:
          type: string
        producer:
          type: string
        Location:
          type: string

    LabelCloneDTO:
      type: object
      properties:
        label:
          $ref: '#/components/schemas/LabelDTO'
        clone:
          $ref: '#/components/schemas/CloneDTO'

    LabelClonesDTO:
      type: object
      properties:
        label:
          $ref: '#/components/schemas/LabelDTO'
        clones:
          type: array
          items:
            $ref: '#/components/schemas/CloneDTO'

    SpecimenCloneDTO:
      allOf:
        - $ref: '#/components/schemas/CloneDTO'
        - type: object
          properties:
            specimenId:
              type: string
            filelocation:
              type: string
            isFlowering:
              type: boolean



    SpecimenUpdateImage:
      type: object
      properties:
        file:
          type: string
          format: binary

    SpecimenUpdateSex:
      type: object
      properties:
        file:
          type: string
          format: binary


    SpecimenUpdateFlowerStatus:
      type: object
      properties:
        isFlowering:
          type: boolean

    GrowlistPublic:
      type: object
      properties:
        isFlowering:
          type: boolean







    GrowlistDTO:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        specimens:
          type: array
          items:
            $ref: '#/components/schemas/SpecimenCloneDTO'

    # since Spring boot open api generator does not generate allowed Values
    NepenthesType:
      type: string
      enum:
        - Species
        - MultiHybrid
        - PrimaryHybrid
      x-enum-varnames:
        - species
        - multihybrid
        - primaryhybrid
      x-enumNames:
        - species
        - multihybrid
        - primaryhybrid

    CloneType:
      type: string
      enum: &CloneType
        - iv
        - ic
      x-enum-varnames: *CloneType
      x-enumNames:
        - iv
        - ic















