openapi: 3.0.0
tags:
  - name: NepenthesManagement
    description: Operations to manage Nepenthes
info:
  title: Nepflow Nepenthes
  description: |-
    API for Nepenthes Operations
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:4200/api

paths:
  /nepenthes:
    get:
      summary: get all nepenthes
      tags:
        - NepenthesManagement
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NepenthesDTO'
        '404':
          description: No nepenthes found
    post:
      summary: Create new nepenthes
      tags:
        - NepenthesManagement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NepenthesDTO'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NepenthesDTO'
        '404':
          description: No nepenthes found
  /nepenthes/{name}:
    get:
      summary: get a nepenthes and their clones
      tags:
        - NepenthesManagement
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NepenthesClonesDTO'
        '404':
          description: nepenthes not found
  /nepenthes/{name}/{clone}:
    get:
      tags:
        - NepenthesManagement
      summary: get s specific clone
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true

        - in: path
          name: clone
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ICCloneDTO'
                  - $ref: '#/components/schemas/IVCloneDTO'

        '404':
          description: Clone does not exist
  /location:
    post:
      summary: add a new Location
      tags:
        - NepenthesManagement
      requestBody:
        description: LocationdTo with all necessary Attributes
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocationDTO'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationDTO'
        '500':
          description: Internal Error
  /producer:
    post:
      summary: add a new Producer
      tags:
        - NepenthesManagement
      requestBody:
        description: DTO with all necessary Attributes
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProducerDTO'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProducerDTO'
        '500':
          description: Internal Error

  /clone/species/:
    get:
      summary: get all Species Clones
      tags:
        - NepenthesManagement
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  anyOf:
                    - $ref: '#/components/schemas/IVCloneDTO'
                    - $ref: '#/components/schemas/ICCloneDTO'
  /clone/species/iv:
    post:
      summary: add a new iv clone of a nepenthes
      tags:
        - NepenthesManagement
      requestBody:
        description: Clone DTO with new values
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IVCloneDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IVCloneDTO'
    put:
      tags:
        - NepenthesManagement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IVCloneDTO'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IVCloneDTO'
        '404':
          description: No nepenthes found
  /clone/species/ic:
    post:
      summary: add a new iv clone of a nepenthes
      tags:
        - NepenthesManagement
      requestBody:
        description: Clone DTO with new values
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ICCloneDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ICCloneDTO'
    put:
      tags:
        - NepenthesManagement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ICCloneDTO'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ICCloneDTO'
        '404':
          description: No nepenthes found

  /clone/hybrids/:
    get:
      summary: get all Species Clones
      tags:
        - NepenthesManagement
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  anyOf:
                    - $ref: '#/components/schemas/ICCloneDTO'
                    - $ref: '#/components/schemas/IVCloneDTO'
  /clone/hybrids/iv:
    post:
      summary: add a new iv hybrid
      tags:
        - NepenthesManagement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IVCloneDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IVCloneDTO'
    put:
      tags:
        - NepenthesManagement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IVCloneDTO'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IVCloneDTO'
        '404':
          description: No nepenthes found
  /clone/hybrids/ic:
    post:
      summary: add a new iv hybrid clone
      tags:
        - NepenthesManagement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ICCloneDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ICCloneDTO'
    put:
      tags:
        - NepenthesManagement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ICCloneDTO'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ICCloneDTO'
        '404':
          description: No nepenthes found

  /clone/multi-hybrid/:
    get:
      summary: get all multi-hybrid Clones
      tags:
        - NepenthesManagement
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  anyOf:
                    - $ref: '#/components/schemas/ICCloneDTO'
                    - $ref: '#/components/schemas/IVCloneDTO'
  /clone/multi-hybrid/iv:
    post:
      summary: add a new iv multi-hybrid
      tags:
        - NepenthesManagement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IVCloneDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IVCloneDTO'
    put:
      tags:
        - NepenthesManagement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IVCloneDTO'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IVCloneDTO'
        '404':
          description: No nepenthes found
  /clone/multi-hybrid/ic:
    post:
      summary: add a new iv multi-hybrid clone
      tags:
        - NepenthesManagement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ICCloneDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ICCloneDTO'
    put:
      tags:
        - NepenthesManagement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ICCloneDTO'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ICCloneDTO'
        '404':
          description: No nepenthes found



components:
  schemas:
    NepenthesDTO:
      type: string

    LocationDTO:
      type: string

    ProducerDTO:
      type: string


    CloneGrexDTO:
      type: object
      properties:
        cloneId:
          type: string
        father:
          oneOf:
            - $ref: '#/components/schemas/ICCloneDTO'
            - $ref: '#/components/schemas/IVCloneDTO'
        mother:
          oneOf:
            - $ref: '#/components/schemas/ICCloneDTO'
            - $ref: '#/components/schemas/IVCloneDTO'

    # will be also used for IC Hybrids and MultiHybrids
    ICCloneDTO:
      type: object
      properties:
        cloneId:
          type: string
        name:
          type: string
        sex:
          type: string
        nepenthesName:
          $ref: '#/components/schemas/CloneGrexDTO'
        Location:
          $ref: '#/components/schemas/LocationDTO'
        grex:
          $ref: '#/components/schemas/CloneGrexDTO'

    # will be also used for IV Hybrids and MultiHybrids
    IVCloneDTO:
      allOf:
        - $ref: '#/components/schemas/ICCloneDTO'
        - type: object
          required:
            - producer
          properties:
            producer:
              $ref: '#/components/schemas/ProducerDTO'


    NepenthesClonesDTO:
      type: object
      properties:
        nepenthes:
          $ref: '#/components/schemas/NepenthesDTO'
        clones:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/ICCloneDTO'
              - $ref: '#/components/schemas/IVCloneDTO'
