openapi: 3.0.0
tags:
  - name: NepenthesManagement
    description: Operations to manage Nepenthes
info:
  title: Nepflow Nepenthes
  description: |-
    API for Nepenthes Operations
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/api

paths:
  /location:
    post:
      summary: add a new Location
      tags:
        - NepenthesMetadata
      requestBody:
        description: LocationdTo with all necessary Attributes
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocationDTO'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationDTO'
        '500':
          description: Internal Error
  /producer:
    post:
      summary: add a new Producer
      tags:
        - NepenthesMetadata
      requestBody:
        description: DTO with all necessary Attributes
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProducerDTO'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProducerDTO'
        '500':
          description: Internal Error

  /clone/species/:
    get:
      summary: get all Species
      tags:
        - Species
        - Nepenthes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/LabelDTO'
    post:
      summary: add a new Species
      tags:
        - Species
        - Nepenthes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelClonesDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'

  /clone/species/{name}:
    get:
      summary: get a Species and their clones
      tags:
        - Species
        - Nepenthes
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'
        '404':
          description: nepenthes not found

  /clone/species/iv/{name}:
    parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
    get:
      summary: get all IC Species Clones of a Nepenthes
      tags:
        - Species
        - Nepenthes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'
    post:
      summary: add a new iv clone to a nepenthes
      tags:
        - Species
        - Nepenthes
      requestBody:
        description: Clone DTO with new values
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelClonesDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'
    put:
      tags:
        - Species
        - Nepenthes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelClonesDTO'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'
        '404':
          description: No nepenthes found
  /clone/species/ic:
    get:
      summary: get all IC Species Clones
      tags:
        - Species
        - Nepenthes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/LabelClonesDTO'
  /clone/species/ic/{name}:

    parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
    get:
      summary: get all IC Species Clones of a Nepenthes
      tags:
        - Species
        - Nepenthes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'


    post:
      summary: add a new iv clone to a nepenthes
      tags:
        - Species
        - Nepenthes
      requestBody:
        description: Clone DTO with new values
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelClonesDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'
    put:
      tags:
        - Species
        - Nepenthes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelClonesDTO'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'
        '404':
          description: No nepenthes found


  /clone/primary-hybrid/:
    get:
      summary: get all Primary Hybrids
      tags:
        - PrimaryHybrid
        - Nepenthes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/LabelDTO'

    post:
      summary: add a new Primary Hybrid
      tags:
        - PrimaryHybrid
        - Nepenthes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelClonesDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'



  /clone/primary-hybrid/{name}:
    get:
      summary: get all Primary Hybrid Clones of a Primary Hybrid
      tags:
        - PrimaryHybrid
        - Nepenthes
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'
        '404':
          description: nepenthes not found
  /clone/primary-hybrid/iv/{name}:
    parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
    get:
      summary: get all Primary Hybrid IV Clones
      tags:
        - PrimaryHybrid
        - Nepenthes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'
    post:
      summary: add a new iv clone to a Primary Hybrid
      tags:
        - PrimaryHybrid
        - Nepenthes
      requestBody:
        description: Clone DTO with new values
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelClonesDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'
    put:
      tags:
        - PrimaryHybrid
        - Nepenthes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelClonesDTO'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'
        '404':
          description: No nepenthes found
  /clone/primary-hybrid/ic:
    get:
      summary: get all IC Primary Hybrid Clones
      tags:
        - PrimaryHybrid
        - Nepenthes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/LabelClonesDTO'
  /clone/primary-hybrid/ic/{name}:

    parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
    get:
      summary: get all IC Clones of a Primary Hybrid
      tags:
        - PrimaryHybrid
        - Nepenthes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'


    post:
      summary: add a new iv clone to a Primary Hybrid
      tags:
        - PrimaryHybrid
        - Nepenthes
      requestBody:
        description: Clone DTO with new values
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelClonesDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'
    put:
      tags:
        - PrimaryHybrid
        - Nepenthes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelClonesDTO'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'
        '404':
          description: No nepenthes found


  /clone/multi-hybrid/:
    get:
      summary: get all Multi Hybrids
      tags:
        - MultiHybrid
        - Nepenthes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/LabelDTO'

    post:
      summary: add a new Multi Hybrids
      tags:
        - MultiHybrid
        - Nepenthes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelClonesDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'



  /clone/multi-hybrid/{name}:
    get:
      summary: get all Multi Hybrid Clones of a Multi Hybrid
      tags:
        - MultiHybrid
        - Nepenthes
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'
        '404':
          description: nepenthes not found
  /clone/multi-hybrid/iv/{name}:
    parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
    get:
      summary: get all Multi Hybrid IV Clones
      tags:
        - MultiHybrid
        - Nepenthes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'
    post:
      summary: add a new iv clone to a Multi Hybrid
      tags:
        - MultiHybrid
        - Nepenthes
      requestBody:
        description: Clone DTO with new values
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelClonesDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'
    put:
      tags:
        - MultiHybrid
        - Nepenthes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelClonesDTO'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'
        '404':
          description: No nepenthes found
  /clone/multi-hybrid/ic:
    get:
      summary: get all IC Multi Hybrid Clones
      tags:
        - MultiHybrid
        - Nepenthes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/LabelClonesDTO'
  /clone/multi-hybrid/ic/{name}:

    parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
    get:
      summary: get all IC Clones of a Multi Hybrid
      tags:
        - MultiHybrid
        - Nepenthes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'


    post:
      summary: add a new iv clone to a Multi Hybrid
      tags:
        - MultiHybrid
        - Nepenthes
      requestBody:
        description: Clone DTO with new values
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelClonesDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'
    put:
      tags:
        - MultiHybrid
        - Nepenthes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabelClonesDTO'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelClonesDTO'
        '404':
          description: No nepenthes found






components:
  schemas:

    LocationDTO:
      type: string

    ProducerDTO:
      type: string

    # abstraction of Hybrid/Nepenthes etc.
    LabelDTO:
      type: object
      properties:
        name:
          type: string
        prefix:
          type: string


    CloneDTO:
      type: object
      properties:
        cloneId:
          type: string
        internalcloneId:
          type: string
        sex:
          type: string
        grex:
          $ref: '#/components/schemas/CloneGrexDTO'
        producer:
          $ref: '#/components/schemas/ProducerDTO'
        Location:
          $ref: '#/components/schemas/LocationDTO'


    HybridCloneDTO:
      allOf:
        - $ref: '#/components/schemas/CloneDTO'
        - type: object
          properties:
            fatherName:
              type: string
            motherName:
              type: string


    CloneGrexDTO:
      type: object
      properties:
        cloneId:
          type: string
        father:
          oneOf:
            - $ref: '#/components/schemas/CloneDTO'
            - $ref: '#/components/schemas/HybridCloneDTO'
        mother:
          oneOf:
            - $ref: '#/components/schemas/CloneDTO'
            - $ref: '#/components/schemas/HybridCloneDTO'


    LabelClonesDTO:
      type: object
      properties:
        label:
          $ref: '#/components/schemas/LabelDTO'
        clones:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/CloneDTO'
              - $ref: '#/components/schemas/HybridCloneDTO'
