spring:
  profiles:
    active: default
  server:
    port: 8080
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password


okta:
  oauth2:
    issuer: https://dev-562zgyhcw56114ld.eu.auth0.com/
    client-id: c6CZP4ZEGbWdIeonARthJJAquBvTleWx
    client-secret: 47IoidD09pCLoOIeEXQOHsDA3ePI0NL4bVbt8Ps1ssJFPBCzFTUZDzKDQ96HOri8



jackson:
  date-format: org.openapitools.RFC3339DateFormat
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false
