openapi: 3.0.0
info:
  description: API for Growlist Operations
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Nepflow User
  version: 1.0.0
servers:
- url: http://localhost:4200/api
tags:
- description: Operations to add/remove Plants to the Useraccount
  name: Growlistmanagement
paths:
  /user/nepenthes:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/UserCloneDTO'
                type: array
          description: OK
        "404":
          description: User not found
      summary: get all nepenthes of currently logged in User
      tags:
      - Growlistmanagement
      x-accepts: application/json
      x-tags:
      - tag: Growlistmanagement
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCloneDTO'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCloneDTO'
          description: OK
        "500":
          description: "Error, could not add Nepenthes Clone to user"
      summary: Add Clone of a Nepenthes to currently logged in User
      tags:
      - Growlistmanagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: Growlistmanagement
  /{user}/nepenthes:
    get:
      parameters:
      - explode: false
        in: path
        name: user
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/UserCloneDTO'
                type: array
          description: OK
        "404":
          description: "Error, User not found"
      summary: get Nepenthes of a specific User
      tags:
      - Growlistmanagement
      x-accepts: application/json
      x-tags:
      - tag: Growlistmanagement
components:
  schemas:
    UserCloneDTO:
      example:
        nepenthesName: nepenthesName
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        cloneId: cloneId
        user: user
      properties:
        id:
          format: uuid
          type: string
        cloneId:
          type: string
        nepenthesName:
          type: string
        user:
          description: Name of the User who grows this specific Clone
          type: string
      type: object
