openapi: 3.0.0
info:
  description: API for Nepenthes Operations
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Nepflow Nepenthes
  version: 1.0.0
servers:
- url: http://localhost:8080/api
tags:
- description: Operations to manage Nepenthes
  name: NepenthesManagement
paths:
  /nepenthes:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/NepenthesDTO'
                type: array
          description: OK
        "404":
          description: No nepenthes found
      summary: get all nepenthes
      tags:
      - NepenthesManagement
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NepenthesDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NepenthesDTO'
          description: OK
        "404":
          description: No nepenthes found
      summary: Create new nepenthes
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /nepenthes/{name}:
    get:
      parameters:
      - explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NepenthesClonesDTO'
          description: OK
        "404":
          description: nepenthes not found
      summary: get a nepenthes and their clones
      tags:
      - NepenthesManagement
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /nepenthes/{name}/{clone}:
    get:
      parameters:
      - explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: clone
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_nepenthes__name___clone__get_200_response'
          description: OK
        "404":
          description: Clone does not exist
      summary: get s specific clone
      tags:
      - NepenthesManagement
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /location:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LocationDTO'
        description: LocationdTo with all necessary Attributes
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocationDTO'
          description: OK
        "500":
          description: Internal Error
      summary: add a new Location
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /producer:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProducerDTO'
        description: DTO with all necessary Attributes
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProducerDTO'
          description: OK
        "500":
          description: Internal Error
      summary: add a new Producer
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /clone/species/:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_clone_species__get_200_response_inner'
                type: array
          description: OK
      summary: get all Species Clones
      tags:
      - NepenthesManagement
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /clone/species/iv:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IVCloneDTO'
        description: Clone DTO with new values
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IVCloneDTO'
          description: OK
      summary: add a new iv clone of a nepenthes
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IVCloneDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IVCloneDTO'
          description: OK
        "404":
          description: No nepenthes found
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /clone/species/ic:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ICCloneDTO'
        description: Clone DTO with new values
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ICCloneDTO'
          description: OK
      summary: add a new iv clone of a nepenthes
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ICCloneDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ICCloneDTO'
          description: OK
        "404":
          description: No nepenthes found
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /clone/hybrids/:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_clone_hybrids__get_200_response_inner'
                type: array
          description: OK
      summary: get all Species Clones
      tags:
      - NepenthesManagement
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /clone/hybrids/iv:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IVCloneDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IVCloneDTO'
          description: OK
      summary: add a new iv hybrid
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IVCloneDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IVCloneDTO'
          description: OK
        "404":
          description: No nepenthes found
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /clone/hybrids/ic:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ICCloneDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ICCloneDTO'
          description: OK
      summary: add a new iv hybrid clone
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ICCloneDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ICCloneDTO'
          description: OK
        "404":
          description: No nepenthes found
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /clone/multi-hybrid/:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_clone_hybrids__get_200_response_inner'
                type: array
          description: OK
      summary: get all multi-hybrid Clones
      tags:
      - NepenthesManagement
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /clone/multi-hybrid/iv:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IVCloneDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IVCloneDTO'
          description: OK
      summary: add a new iv multi-hybrid
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IVCloneDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IVCloneDTO'
          description: OK
        "404":
          description: No nepenthes found
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /clone/multi-hybrid/ic:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ICCloneDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ICCloneDTO'
          description: OK
      summary: add a new iv multi-hybrid clone
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ICCloneDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ICCloneDTO'
          description: OK
        "404":
          description: No nepenthes found
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
components:
  schemas:
    NepenthesDTO:
      type: string
    LocationDTO:
      type: string
    ProducerDTO:
      type: string
    CloneGrexDTO:
      example:
        mother: null
        father: null
        cloneId: cloneId
      properties:
        cloneId:
          type: string
        father:
          $ref: '#/components/schemas/_nepenthes__name___clone__get_200_response'
        mother:
          $ref: '#/components/schemas/_nepenthes__name___clone__get_200_response'
      type: object
    ICCloneDTO:
      example:
        nepenthes: nepenthes
        sex: sex
        name: name
        cloneId: cloneId
        grex:
          mother: null
          father: null
          cloneId: cloneId
        Location: Location
      properties:
        cloneId:
          type: string
        name:
          type: string
        sex:
          type: string
        nepenthes:
          type: string
        Location:
          type: string
        grex:
          $ref: '#/components/schemas/CloneGrexDTO'
      type: object
    IVCloneDTO:
      allOf:
      - $ref: '#/components/schemas/ICCloneDTO'
      - properties:
          producer:
            $ref: '#/components/schemas/ProducerDTO'
        required:
        - producer
        type: object
    NepenthesClonesDTO:
      example:
        nepenthes: nepenthes
        clones:
        - null
        - null
      properties:
        nepenthes:
          type: string
        clones:
          items:
            $ref: '#/components/schemas/_clone_hybrids__get_200_response_inner'
          type: array
      type: object
    _nepenthes__name___clone__get_200_response:
      oneOf:
      - $ref: '#/components/schemas/ICCloneDTO'
      - $ref: '#/components/schemas/IVCloneDTO'
      x-one-of-name: NepenthesNameCloneGet200Response
    _clone_species__get_200_response_inner:
      anyOf:
      - $ref: '#/components/schemas/IVCloneDTO'
      - $ref: '#/components/schemas/ICCloneDTO'
    _clone_hybrids__get_200_response_inner:
      anyOf:
      - $ref: '#/components/schemas/ICCloneDTO'
      - $ref: '#/components/schemas/IVCloneDTO'
