openapi: 3.0.0
info:
  description: API for Nepenthes Operations
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Nepflow Nepenthes
  version: 1.0.0
servers:
- url: http://localhost:4200/api
tags:
- description: Operations to manage Nepenthes
  name: NepenthesManagement
paths:
  /nepenthes:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/NepenthesDTO'
                type: array
          description: OK
        "404":
          description: No nepenthes found
      summary: get all nepenthes
      tags:
      - NepenthesManagement
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NepenthesDTO'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NepenthesDTO'
          description: OK
        "404":
          description: No nepenthes found
      summary: Create new nepenthes
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /nepenthes/{name}:
    get:
      parameters:
      - explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NepenthesClonesDTO'
          description: OK
        "404":
          description: nepenthes not found
      summary: get a nepenthes and their clones
      tags:
      - NepenthesManagement
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /nepenthes/{name}/{clone}:
    get:
      parameters:
      - explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: clone
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_nepenthes__name___clone__get_200_response'
          description: OK
        "404":
          description: Clone does not exist
      summary: get s specific clone
      tags:
      - NepenthesManagement
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /clone/iv:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IVCloneDTO'
        description: Clone DTO with new values
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IVCloneDTO'
          description: OK
        "404":
          description: No nepenthes found
      summary: add a new iv clone of a nepenthes
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IVCloneDTO'
        description: Clone DTO with new values
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IVCloneDTO'
          description: OK
        "404":
          description: No nepenthes found
      summary: change information of an existing clone
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /clone/ic:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CloneDTO'
        description: Clone DTO with new values
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloneDTO'
          description: OK
        "404":
          description: No nepenthes found
      summary: add a new ic clone of a nepenthes
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CloneDTO'
        description: Clone DTO with new values
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloneDTO'
          description: OK
        "404":
          description: No nepenthes found
      summary: change information of an existing clone
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /mountain:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MountainDTO'
        description: MountainDTO with all necessary Attributes
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MountainDTO'
          description: OK
        "500":
          description: Internal Error
      summary: add a new Mountain
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
  /producer:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProducerDTO'
        description: DTO with all necessary Attributes
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProducerDTO'
          description: OK
        "500":
          description: Internal Error
      summary: add a new Producer
      tags:
      - NepenthesManagement
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: NepenthesManagement
components:
  schemas:
    NepenthesDTO:
      type: string
    MountainDTO:
      type: string
    ProducerDTO:
      type: string
    CloneDTO:
      example:
        nepenthes: nepenthes
        mountain: mountain
        sex: sex
        id: id
      properties:
        id:
          type: string
        nepenthes:
          type: string
        mountain:
          type: string
        sex:
          type: string
      type: object
    IVCloneDTO:
      allOf:
      - $ref: '#/components/schemas/CloneDTO'
      - properties:
          producer:
            $ref: '#/components/schemas/ProducerDTO'
        required:
        - producer
        type: object
    NepenthesClonesDTO:
      example:
        nepenthes: nepenthes
        clones:
        - null
        - null
      properties:
        nepenthes:
          type: string
        clones:
          items:
            $ref: '#/components/schemas/NepenthesClonesDTO_clones_inner'
          type: array
      type: object
    _nepenthes__name___clone__get_200_response:
      oneOf:
      - $ref: '#/components/schemas/CloneDTO'
      - $ref: '#/components/schemas/IVCloneDTO'
      x-one-of-name: NepenthesNameCloneGet200Response
    NepenthesClonesDTO_clones_inner:
      anyOf:
      - $ref: '#/components/schemas/CloneDTO'
      - $ref: '#/components/schemas/IVCloneDTO'
