name: Nepflow Gradle Test Action
on: push
jobs:
  my-jobname:
    runs-on: ubuntu-latest
    env:
       JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
    steps:
      - name: Submit sonar qube report
        if: ${{ env.JASYPT_ENCRYPTOR_PASSWORD == 'true' }}
        run: echo "I have the token!"
        env:
           JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
