name: Nepflow Gradle Test Action
on: push
jobs:
  my-jobname:
    runs-on: ubuntu-latest
    env:
       JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
    steps:
      - name: test JASYPT_ENCRYPTOR_PASSWORD exists
      run: |
      example-command "$JASYPT_ENCRYPTOR_PASSWORD"
        env:
           JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
