name: Nepflow Gradle Test Action
on:
  push:
    paths:
    - "nepflow/**"
  

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      neo4j:
        image: neo4j
        # prevent change password dialog
        env:
          NEO4J_AUTH: neo4j/password
        ports:
          - 7687:7687

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: install java
        uses: actions/setup-java@v2
        with:
              java-version: '21'
              distribution: 'zulu'
              
              
      - name: Check if JASYPT_ENCRYPTOR_PASSWORD is set
        env:
            JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}

        run: |
          if [ -z "$JASYPT_ENCRYPTOR_PASSWORD" ]; then
            echo "Error: Environment variable 'JASYPT_ENCRYPTOR_PASSWORD' is not set. Please set the environment variable or pass it as a secret."
            exit 1
          else
            echo "Environment variable 'JASYPT_ENCRYPTOR_PASSWORD' is set."
          fi
      - name: execute Tests
        env:
            JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
        run:  cd nepflow && chmod +x gradlew && ./gradlew test --tests "com.nepflow.*" -P password="$JASYPT_ENCRYPTOR_PASSWORD"
