name: Nepflow Gradle Test Action
on:
  push:
    paths:
    - "nepflow/**"
  

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      neo4j:
        image: neo4j
        # prevent change password dialog
        env:
          NEO4J_AUTH: neo4j/password
        ports:
          - 7687:7687

    steps:
      - name: "check if JASYPT_ENCRYPTOR_PASSWORD exists"
        env: 
            JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
        if: ${{ env.JASYPT_ENCRYPTOR_PASSWORD == '' }}
        run: 'echo "echo the secret \"JASYPT_ENCRYPTOR_PASSWORD\" has not been made; echo please go to \"settings \> secrets \> actions\" to create it"

      - name: Check out repository code
        uses: actions/checkout@v4
      - name: install java
        uses: actions/setup-java@v2
        with:
              java-version: '21'
              distribution: 'zulu'
                   
      - name: execute Tests
        env:
            JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
        run:  cd nepflow && chmod +x gradlew && ./gradlew test --tests "com.nepflow.*" -P password="$JASYPT_ENCRYPTOR_PASSWORD"
