name: Nepflow Gradle Test Action
on: push
  
jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      neo4j:
        image: neo4j
        # prevent change password dialog
        env:
          NEO4J_AUTH: neo4j/password
        ports:
          - 7687:7687

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: install java
        uses: actions/setup-java@v2
        with:
              java-version: '21'
              distribution: 'zulu'
      - name: execute Tests
        run:  cd nepflow && chmod +x gradlew && ./gradlew test --tests "com.nepflow.*" -P password="jeöö" 
        env:
            jasypt.encryptor.password: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}